package com.thangit.boardinghouse.service.impl;

import com.thangit.boardinghouse.common.exception.AuthException;
import com.thangit.boardinghouse.domain.auth.RoleCode;
import com.thangit.boardinghouse.dto.request.accountant.AccountantRequests.*;
import com.thangit.boardinghouse.repository.AccountantPortalRepository;
import com.thangit.boardinghouse.security.AuthenticatedUser;
import com.thangit.boardinghouse.service.AccountantPortalService;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AccountantPortalServiceImpl implements AccountantPortalService {
    private final AccountantPortalRepository repository;
    public AccountantPortalServiceImpl(AccountantPortalRepository repository){this.repository=repository;}

    @Override @Transactional(readOnly=true) public Map<String,Object> dashboard(AuthenticatedUser p,Long propertyId,String period){accountant(p);scope(p,propertyId);return repository.dashboard(p.id(),propertyId,period(period));}
    @Override @Transactional(readOnly=true) public Map<String,Object> invoices(AuthenticatedUser p,Long propertyId,String period,String status,String keyword,int page,int size){accountant(p);scope(p,propertyId);page(page,size);return repository.pageInvoices(p.id(),propertyId,period(period),status,keyword,page,size);}
    @Override @Transactional(readOnly=true) public Map<String,Object> invoice(AuthenticatedUser p,long id){accountant(p);Map<String,Object> invoice=invoice(p,id,false);Map<String,Object> result=new LinkedHashMap<>(invoice);result.put("items",repository.invoiceItems(id));result.put("payments",repository.invoicePayments(id));return result;}
    @Override @Transactional public Map<String,Object> issueInvoice(AuthenticatedUser p,long id,Versioned request){accountant(p);permission(p,"can_issue_invoice");Map<String,Object> invoice=invoice(p,id,true);unlocked(property(invoice),date(invoice,"issue_date",LocalDate.now()));changed(repository.issueInvoice(id,p.id(),request.version()),"INVOICE_VERSION_CONFLICT","Hóa đơn đã thay đổi hoặc không còn ở trạng thái có thể phát hành.");repository.audit(property(invoice),p.id(),"INVOICE",id,"ISSUED",null);return invoice(p,id);}

    @Override @Transactional(readOnly=true) public Map<String,Object> payments(AuthenticatedUser p,Long propertyId,String period,String status,String keyword,int page,int size){accountant(p);scope(p,propertyId);page(page,size);return repository.pagePayments(p.id(),propertyId,period(period),status,keyword,page,size);}
    @Override @Transactional(readOnly=true) public Map<String,Object> payment(AuthenticatedUser p,long id){accountant(p);return repository.payment(p.id(),id,false).orElseThrow(()->notFound("PAYMENT_NOT_FOUND","Không tìm thấy giao dịch trong phạm vi được giao."));}
    @Override @Transactional public Map<String,Object> createPayment(AuthenticatedUser p,String key,PaymentCreate request){accountant(p);permission(p,"can_record_payment");if(key==null||key.isBlank()||key.length()>100)throw bad("IDEMPOTENCY_KEY_REQUIRED","Cần Idempotency-Key hợp lệ để tránh ghi nhận thanh toán trùng.");Optional<Map<String,Object>> existing=repository.paymentByKey(key.trim());if(existing.isPresent())return existing.get();Map<String,Object> invoice=invoice(p,request.invoiceId(),true);unlocked(property(invoice),request.paidAt().toLocalDate());String status=text(invoice,"status");if(List.of("DRAFT","CANCELLED","PAID").contains(status))throw conflict("INVOICE_NOT_PAYABLE","Hóa đơn không ở trạng thái có thể thanh toán.");BigDecimal remaining=money(invoice,"remaining_amount");if(request.amount().compareTo(remaining)>0)throw bad("PAYMENT_EXCEEDS_DEBT","Số tiền không được vượt quá dư nợ hóa đơn.");try{long id=repository.createPayment(invoice,request,p.id(),key.trim());repository.allocation(id,request.invoiceId(),request.amount());changed(repository.applyPayment(request.invoiceId(),request.amount(),number(invoice,"version")),"INVOICE_VERSION_CONFLICT","Hóa đơn vừa được cập nhật, chưa ghi nhận thanh toán.");Long receiptId=request.issueReceipt()?repository.receipt(id,invoice,request.amount(),p.id(),request.note()):null;repository.audit(property(invoice),p.id(),"PAYMENT",id,"CONFIRMED","Phân bổ vào hóa đơn "+text(invoice,"code"));Map<String,Object> result=new LinkedHashMap<>(repository.payment(p.id(),id,false).orElseThrow());result.put("receiptId",receiptId);return result;}catch(DuplicateKeyException e){return repository.paymentByKey(key.trim()).orElseThrow(()->conflict("PAYMENT_DUPLICATE","Giao dịch hoặc mã tham chiếu đã tồn tại."));}}
    @Override @Transactional public Map<String,Object> reversePayment(AuthenticatedUser p,long id,Reason request){accountant(p);permission(p,"can_create_adjustment");Map<String,Object> payment=repository.payment(p.id(),id,true).orElseThrow(()->notFound("PAYMENT_NOT_FOUND","Không tìm thấy giao dịch."));unlocked(property(payment),LocalDate.now());if(!"CONFIRMED".equals(text(payment,"status")))throw conflict("PAYMENT_NOT_REVERSIBLE","Chỉ giao dịch đã xác nhận mới có thể đảo.");changed(repository.reversePayment(id,p.id(),request.reason()),"PAYMENT_VERSION_CONFLICT","Giao dịch đã thay đổi.");repository.reverseAllocation(id);repository.reverseInvoice(number(payment,"invoice_id"),money(payment,"amount"));repository.audit(property(payment),p.id(),"PAYMENT",id,"REVERSED",request.reason());return repository.payment(p.id(),id,false).orElseThrow();}

    @Override @Transactional(readOnly=true) public Map<String,Object> proofs(AuthenticatedUser p,Long propertyId,String status,int page,int size){accountant(p);scope(p,propertyId);page(page,size);return repository.pageProofs(p.id(),propertyId,status,page,size);}
    @Override @Transactional public Map<String,Object> approveProof(AuthenticatedUser p,long id,String key,ProofDecision request){accountant(p);permission(p,"can_review_proof");Map<String,Object> proof=repository.proof(p.id(),id,true).orElseThrow(()->notFound("PROOF_NOT_FOUND","Không tìm thấy minh chứng thanh toán."));if(!"PENDING".equals(text(proof,"status")))throw conflict("PROOF_ALREADY_REVIEWED","Minh chứng đã được xử lý.");BigDecimal amount=money(proof,"amount");if(amount.compareTo(money(proof,"remaining_amount"))>0)throw bad("PROOF_EXCEEDS_DEBT","Số tiền trên minh chứng vượt dư nợ hiện tại.");PaymentCreate payment=new PaymentCreate(number(proof,"invoice_id"),amount,"BANK_TRANSFER",dateTime(proof,"transferred_at"),text(proof,"transaction_reference"),request.note(),request.issueReceipt());Map<String,Object> created=createPayment(p,key,payment);changed(repository.approveProof(id,p.id()),"PROOF_ALREADY_REVIEWED","Minh chứng đã được xử lý.");repository.audit(property(proof),p.id(),"PAYMENT_PROOF",id,"APPROVED",request.note());return created;}
    @Override @Transactional public Map<String,Object> rejectProof(AuthenticatedUser p,long id,Reason request){accountant(p);permission(p,"can_review_proof");Map<String,Object> proof=repository.proof(p.id(),id,true).orElseThrow(()->notFound("PROOF_NOT_FOUND","Không tìm thấy minh chứng thanh toán."));changed(repository.rejectProof(id,p.id(),request.reason()),"PROOF_ALREADY_REVIEWED","Minh chứng đã được xử lý.");repository.audit(property(proof),p.id(),"PAYMENT_PROOF",id,"REJECTED",request.reason());return repository.proof(p.id(),id,false).orElseThrow();}

    @Override @Transactional(readOnly=true) public Map<String,Object> debts(AuthenticatedUser p,Long propertyId,String keyword,int page,int size){accountant(p);scope(p,propertyId);page(page,size);return repository.pageDebts(p.id(),propertyId,keyword,page,size);}
    @Override @Transactional(readOnly=true) public Map<String,Object> tenantDebts(AuthenticatedUser p,long tenantId,Long propertyId,int page,int size){accountant(p);scope(p,propertyId);page(page,size);return repository.pageTenantDebts(p.id(),tenantId,propertyId,page,size);}
    @Override @Transactional public void reminder(AuthenticatedUser p,long invoiceId,Reminder request){accountant(p);Map<String,Object> invoice=invoice(p,invoiceId,false);repository.reminder(invoiceId,p.id(),request);repository.audit(property(invoice),p.id(),"INVOICE",invoiceId,"REMINDER_SENT",request.channel());}
    @Override @Transactional public void promise(AuthenticatedUser p,long invoiceId,PromiseCreate request){accountant(p);Map<String,Object> invoice=invoice(p,invoiceId,false);if(request.amount().compareTo(money(invoice,"remaining_amount"))>0)throw bad("PROMISE_EXCEEDS_DEBT","Số tiền cam kết không được vượt dư nợ.");repository.promise(invoiceId,p.id(),request);repository.audit(property(invoice),p.id(),"INVOICE",invoiceId,"PAYMENT_PROMISE_CREATED",request.note());}

    @Override @Transactional(readOnly=true) public Map<String,Object> deposits(AuthenticatedUser p,Long propertyId,int page,int size){accountant(p);scope(p,propertyId);page(page,size);return repository.pageDeposits(p.id(),propertyId,page,size);}
    @Override @Transactional(readOnly=true) public Map<String,Object> deposit(AuthenticatedUser p,long id){accountant(p);return repository.deposit(p.id(),id,false).orElseThrow(()->notFound("DEPOSIT_NOT_FOUND","Không tìm thấy khoản tiền cọc."));}
    @Override @Transactional public Map<String,Object> deposit(AuthenticatedUser p,long id,DepositTransaction request){accountant(p);permission(p,"can_record_payment");Map<String,Object> deposit=repository.deposit(p.id(),id,true).orElseThrow(()->notFound("DEPOSIT_NOT_FOUND","Không tìm thấy khoản tiền cọc."));unlocked(property(deposit),LocalDate.now());changed(repository.applyDeposit(id,request),"DEPOSIT_VERSION_CONFLICT","Tiền cọc đã thay đổi hoặc số dư không đủ.");repository.depositTransaction(id,p.id(),request);repository.audit(property(deposit),p.id(),"DEPOSIT",id,request.type(),request.reason());return repository.deposit(p.id(),id,false).orElseThrow();}

    @Override @Transactional(readOnly=true) public Map<String,Object> vouchers(AuthenticatedUser p,Long propertyId,String status,int page,int size){accountant(p);scope(p,propertyId);page(page,size);return repository.pageVouchers(p.id(),propertyId,status,page,size);}
    @Override @Transactional(readOnly=true) public Map<String,Object> voucher(AuthenticatedUser p,long id){accountant(p);return repository.voucher(p.id(),id).orElseThrow(()->notFound("VOUCHER_NOT_FOUND","Không tìm thấy phiếu chi."));}
    @Override @Transactional public Map<String,Object> createVoucher(AuthenticatedUser p,VoucherCreate request){accountant(p);permission(p,"can_create_voucher");scope(p,request.propertyId());unlocked(request.propertyId(),request.voucherDate());long id=repository.voucher(p.id(),request);repository.audit(request.propertyId(),p.id(),"PAYMENT_VOUCHER",id,"DRAFT_CREATED",request.description());return voucher(p,id);}
    @Override @Transactional public Map<String,Object> submitVoucher(AuthenticatedUser p,long id,Versioned request){accountant(p);Map<String,Object> voucher=voucher(p,id);unlocked(property(voucher),date(voucher,"voucher_date",LocalDate.now()));changed(repository.submitVoucher(p.id(),id,request.version()),"VOUCHER_VERSION_CONFLICT","Phiếu chi đã thay đổi hoặc không còn là bản nháp của bạn.");repository.audit(property(voucher),p.id(),"PAYMENT_VOUCHER",id,"SUBMITTED","Kế toán gửi duyệt; không tự phê duyệt.");return voucher(p,id);}
    @Override @Transactional(readOnly=true) public Map<String,Object> otherIncome(AuthenticatedUser p,Long propertyId,String period,int page,int size){accountant(p);scope(p,propertyId);page(page,size);return repository.pageOtherIncome(p.id(),propertyId,period(period),page,size);}
    @Override @Transactional public Map<String,Object> createOtherIncome(AuthenticatedUser p,OtherIncomeCreate request){accountant(p);permission(p,"can_record_payment");scope(p,request.propertyId());unlocked(request.propertyId(),request.incomeDate());long id=repository.otherIncome(p.id(),request);repository.audit(request.propertyId(),p.id(),"OTHER_INCOME",id,"CONFIRMED",request.description());return repository.otherIncome(p.id(),id).orElseThrow();}

    @Override @Transactional(readOnly=true) public Map<String,Object> periods(AuthenticatedUser p,Long propertyId){accountant(p);scope(p,propertyId);return repository.periods(p.id(),propertyId);}
    @Override @Transactional public Map<String,Object> closePeriod(AuthenticatedUser p,long id,PeriodAction request){accountant(p);permission(p,"can_close_period");Map<String,Object> period=repository.period(p.id(),id,true).orElseThrow(()->notFound("PERIOD_NOT_FOUND","Không tìm thấy kỳ kế toán."));changed(repository.closePeriod(id,p.id(),request.version(),request.note()),"PERIOD_VERSION_CONFLICT","Kỳ kế toán đã thay đổi hoặc đã khóa.");repository.audit(property(period),p.id(),"ACCOUNTING_PERIOD",id,"CLOSED",request.note());return repository.period(p.id(),id,false).orElseThrow();}
    @Override @Transactional public Map<String,Object> reopenPeriod(AuthenticatedUser p,long id,PeriodAction request){accountant(p);permission(p,"can_reopen_period");if(request.note()==null||request.note().isBlank())throw bad("REOPEN_REASON_REQUIRED","Cần nhập lý do mở lại kỳ kế toán.");Map<String,Object> period=repository.period(p.id(),id,true).orElseThrow(()->notFound("PERIOD_NOT_FOUND","Không tìm thấy kỳ kế toán."));changed(repository.reopenPeriod(id,p.id(),request.version(),request.note()),"PERIOD_VERSION_CONFLICT","Kỳ kế toán đã thay đổi hoặc đang mở.");repository.audit(property(period),p.id(),"ACCOUNTING_PERIOD",id,"REOPENED",request.note());return repository.period(p.id(),id,false).orElseThrow();}
    @Override @Transactional(readOnly=true) public Map<String,Object> books(AuthenticatedUser p,Long propertyId,String period,String type,int page,int size){accountant(p);scope(p,propertyId);page(page,size);return repository.books(p.id(),propertyId,period(period),type,page,size);}
    @Override @Transactional(readOnly=true) public Map<String,Object> report(AuthenticatedUser p,Long propertyId,String period){accountant(p);scope(p,propertyId);return repository.report(p.id(),propertyId,period(period));}
    @Override @Transactional(readOnly=true) public Map<String,Object> account(AuthenticatedUser p){accountant(p);Map<String,Object> r=new LinkedHashMap<>(repository.profile(p.id()));r.put("properties",repository.properties(p.id()));return r;}
    @Override @Transactional public Map<String,Object> profile(AuthenticatedUser p,ProfileUpdate request){accountant(p);if(repository.emailExists(p.id(),request.email()))throw conflict("EMAIL_EXISTS","Email đã được sử dụng.");repository.updateProfile(p.id(),request);return account(p);}
    @Override @Transactional public Map<String,Object> preferences(AuthenticatedUser p,Preferences request){accountant(p);changed(repository.preferences(p.id(),request),"PROFILE_VERSION_CONFLICT","Hồ sơ đã thay đổi, vui lòng tải lại.");return account(p);}
    @Override @Transactional(readOnly=true) public Object notifications(AuthenticatedUser p){accountant(p);return repository.notifications(p.id());}
    @Override @Transactional public void readNotification(AuthenticatedUser p,long id){accountant(p);changed(repository.readNotification(p.id(),id),"NOTIFICATION_NOT_FOUND","Không tìm thấy thông báo.");}

    private void accountant(AuthenticatedUser p){if(p==null||p.activeRole()!=RoleCode.ACCOUNTANT||!repository.profileExists(p.id()))throw new AuthException(HttpStatus.FORBIDDEN,"ACCOUNTANT_ACCESS_DENIED","Chỉ tài khoản kế toán có hồ sơ hợp lệ được truy cập cổng này.");}
    private void scope(AuthenticatedUser p,Long property){if(property!=null&&!repository.canAccess(p.id(),property))throw new AuthException(HttpStatus.FORBIDDEN,"ACCOUNTANT_PROPERTY_DENIED","Bạn không được phân công cho khu trọ này.");}
    private void permission(AuthenticatedUser p,String permission){if(!repository.permission(p.id(),permission))throw new AuthException(HttpStatus.FORBIDDEN,"ACCOUNTANT_PERMISSION_DENIED","Tài khoản chưa được cấp quyền thực hiện thao tác này.");}
    private Map<String,Object> invoice(AuthenticatedUser p,long id,boolean lock){return repository.invoice(p.id(),id,lock).orElseThrow(()->notFound("INVOICE_NOT_FOUND","Không tìm thấy hóa đơn trong phạm vi được giao."));}
    private void unlocked(long property,LocalDate date){if(repository.locked(property,date))throw conflict("ACCOUNTING_PERIOD_CLOSED","Kỳ kế toán của chứng từ đã khóa; hãy tạo điều chỉnh ở kỳ đang mở.");}
    private static void page(int page,int size){if(page<0||size<1||size>100)throw bad("PAGE_INVALID","Thông tin phân trang không hợp lệ.");}
    private static String period(String p){String value=p==null||p.isBlank()?LocalDate.now().toString().substring(0,7):p;if(!value.matches("\\d{4}-(0[1-9]|1[0-2])"))throw bad("PERIOD_INVALID","Kỳ kế toán phải có định dạng YYYY-MM.");return value;}
    private static long property(Map<String,Object> m){return number(m,"property_id");}
    private static long number(Map<String,Object> m,String key){Object value=m.get(key);if(value instanceof Number n)return n.longValue();throw bad("DATA_INVALID","Dữ liệu "+key+" không hợp lệ.");}
    private static BigDecimal money(Map<String,Object> m,String key){Object value=m.get(key);return value instanceof BigDecimal b?b:new BigDecimal(value.toString());}
    private static String text(Map<String,Object> m,String key){Object value=m.get(key);return value==null?null:value.toString();}
    private static LocalDate date(Map<String,Object> m,String key,LocalDate fallback){Object value=m.get(key);if(value instanceof LocalDate d)return d;if(value instanceof java.sql.Date d)return d.toLocalDate();return fallback;}
    private static LocalDateTime dateTime(Map<String,Object> m,String key){Object value=m.get(key);if(value instanceof LocalDateTime d)return d;if(value instanceof Timestamp t)return t.toLocalDateTime();throw bad("DATE_INVALID","Ngày giao dịch không hợp lệ.");}
    private static void changed(int n,String code,String message){if(n==0)throw conflict(code,message);}
    private static AuthException bad(String code,String message){return new AuthException(HttpStatus.BAD_REQUEST,code,message);}
    private static AuthException conflict(String code,String message){return new AuthException(HttpStatus.CONFLICT,code,message);}
    private static AuthException notFound(String code,String message){return new AuthException(HttpStatus.NOT_FOUND,code,message);}
}
