package com.thangit.boardinghouse.service.impl;

import com.thangit.boardinghouse.common.exception.AuthException;
import com.thangit.boardinghouse.domain.auth.RoleCode;
import com.thangit.boardinghouse.dto.request.invoice.AdminInvoiceRequests.*;
import com.thangit.boardinghouse.dto.response.invoice.AdminInvoiceResponses.*;
import com.thangit.boardinghouse.repository.AdminInvoiceRepository;
import com.thangit.boardinghouse.security.AuthenticatedUser;
import com.thangit.boardinghouse.service.AdminInvoiceService;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.sql.Date;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AdminInvoiceServiceImpl implements AdminInvoiceService {
 private final AdminInvoiceRepository repo; public AdminInvoiceServiceImpl(AdminInvoiceRepository repo){this.repo=repo;}
 @Override @Transactional(readOnly=true) public Summary summary(AuthenticatedUser p,Long propertyId,String period){read(p);if(propertyId!=null)property(p,propertyId);return repo.summary(p.id(),p.activeRole(),propertyId,period);}
 @Override @Transactional(readOnly=true) public InvoiceOptions options(AuthenticatedUser p){read(p);return new InvoiceOptions(repo.properties(p.id(),p.activeRole()),repo.buildings(p.id(),p.activeRole()),repo.floors(p.id(),p.activeRole()),repo.rooms(p.id(),p.activeRole()),repo.contracts(p.id(),p.activeRole()));}
 @Override @Transactional(readOnly=true) public Page<InvoiceRow> list(AuthenticatedUser p,Long propertyId,Long buildingId,Long floorId,Long roomId,String keyword,String period,String status,Boolean overdue,BigDecimal min,BigDecimal max,String sort,int page,int size){read(p);if(propertyId!=null)property(p,propertyId);int pg=Math.max(0,page),sz=Math.min(100,Math.max(10,size));return repo.list(p.id(),p.activeRole(),propertyId,buildingId,floorId,roomId,keyword,period,status,overdue,min,max,sort,pg,sz);}
 @Override @Transactional(readOnly=true) public InvoiceDetail detail(AuthenticatedUser p,long id){Map<String,Object> i=accessible(p,id,false);String status=effective(i);boolean draft="DRAFT".equals(status),cancelled="CANCELLED".equals(status),paid="PAID".equals(status);boolean write=canWrite(p);return new InvoiceDetail(id,s(i,"code"),period(date(i,"billing_period")),date(i,"period_start_date"),date(i,"period_end_date"),date(i,"issue_date"),date(i,"due_date"),status,new Party(l(i,"property_id"),s(i,"property_name"),s(i,"property_address")),new Party(l(i,"room_id"),s(i,"room_code"),s(i,"building_name")+" · "+s(i,"floor_name")),new Party(l(i,"tenant_id"),s(i,"tenant_name"),s(i,"tenant_phone")),new Party(l(i,"contract_id"),s(i,"contract_code"),null),repo.items(id),money(i,"subtotal_amount"),money(i,"discount_amount"),money(i,"previous_debt_amount"),money(i,"late_fee_amount"),money(i,"total_amount"),money(i,"paid_amount"),money(i,"remaining_amount"),s(i,"note"),repo.payments(id),repo.adjustments(id),repo.notifications(id),repo.history(id),new Permissions(write&&draft,write&&draft,write&&!draft&&!cancelled&&!paid,write&&!draft&&!cancelled,write&&!draft&&!cancelled,write&&!cancelled&&money(i,"paid_amount").signum()==0,true,true),l(i,"version"));}
 @Override @Transactional public CreateResult create(AuthenticatedUser p,SaveInvoice r){write(p);validateDates(r);Map<String,Object> c=repo.contractForRoom(r.roomId(),r.contractId()).orElseThrow(()->bad("INVOICE_CONTRACT_INVALID","Hợp đồng không thuộc phòng đã chọn."));long propertyId=l(c,"property_id");property(p,propertyId);LocalDate period=LocalDate.parse(r.billingPeriod()+"-01");if(repo.duplicate(r.contractId(),period,null))throw bad("INVOICE_PERIOD_EXISTS","Hóa đơn cho phòng và kỳ này đã tồn tại.");return createCalculated(p,r,c,period,false);}
 private CreateResult createCalculated(AuthenticatedUser p,SaveInvoice r,Map<String,Object> c,LocalDate period,boolean automated){List<CalcItem> items=new ArrayList<>();BigDecimal rent=money(c,"monthly_rent");items.add(new CalcItem("ROOM_RENT","Tiền thuê phòng","Kỳ "+period(period),BigDecimal.ONE,"tháng",rent,rent,"CONTRACT",r.contractId()));int order=1;Map<String,Object> utility=repo.utility(r.contractId(),period).orElse(null);if(utility!=null){addUtility(items,utility,"ELECTRICITY","Tiền điện","electricity_previous","electricity_current","electricity_unit_price","electricity_amount","kWh");addUtility(items,utility,"WATER","Tiền nước","water_previous","water_current","water_unit_price","water_amount","m³");}for(Map<String,Object>x:repo.services(r.contractId(),r.periodEndDate())){BigDecimal price=money(x,"unit_price");items.add(new CalcItem("SERVICE",s(x,"name"),"Dịch vụ theo hợp đồng",BigDecimal.ONE,"tháng",price,price,"CONTRACT_SERVICE",l(x,"id")));}if(r.additionalItems()!=null)for(AdditionalItem x:r.additionalItems()){BigDecimal amount=x.quantity().multiply(x.unitPrice()).setScale(2,RoundingMode.HALF_UP);items.add(new CalcItem("SURCHARGE",x.name(),x.reason(),x.quantity(),x.unit(),x.unitPrice(),amount,"MANUAL",null));}BigDecimal subtotal=items.stream().map(CalcItem::amount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal discount=nvl(r.discountAmount());if(discount.compareTo(subtotal)>0)throw bad("INVOICE_DISCOUNT_INVALID","Giảm giá không được vượt quá tổng khoản thu.");BigDecimal debt=r.includePreviousDebt()?repo.previousDebt(r.contractId(),period):BigDecimal.ZERO;BigDecimal total=subtotal.subtract(discount).add(debt);String status="ISSUE".equals(r.action())?"ISSUED":"DRAFT";String code="HD-"+r.billingPeriod().replace("-","")+"-"+s(c,"room_code")+"-"+String.format("%04d",System.nanoTime()%10000);long id=repo.createInvoice(l(c,"property_id"),r.roomId(),r.contractId(),l(c,"tenant_id"),code,period,r.periodStartDate(),r.periodEndDate(),r.issueDate(),r.dueDate(),subtotal,discount,debt,BigDecimal.ZERO,total,status,r.note(),p.id(),automated);for(CalcItem x:items)repo.addItem(id,x.type(),x.type(),x.name(),x.description(),x.quantity(),x.unit(),x.price(),x.amount(),x.source(),x.sourceId(),order++);repo.history(id,"DRAFT".equals(status)?"CREATED_DRAFT":"CREATED_AND_ISSUED",null,status,null,p.id());return new CreateResult(id,code,status);}
 private void addUtility(List<CalcItem> items,Map<String,Object> u,String type,String name,String prev,String current,String price,String amount,String unit){BigDecimal a=money(u,amount);if(a.signum()>0){BigDecimal qty=money(u,current).subtract(money(u,prev));items.add(new CalcItem(type,name,"Chỉ số "+money(u,prev)+" → "+money(u,current),qty,unit,money(u,price),a,"UTILITY_READING",l(u,"id")));}}
 @Override @Transactional(readOnly=true) public List<BulkPreviewRow> bulkPreview(AuthenticatedUser p,BulkInvoice r){write(p);property(p,r.propertyId());LocalDate period=LocalDate.parse(r.billingPeriod()+"-01");return repo.roomsForBulk(r.propertyId()).stream().map(x->{boolean duplicate=repo.duplicate(l(x,"contract_id"),period,null);return new BulkPreviewRow(l(x,"id"),s(x,"code"),s(x,"tenant_name"),money(x,"monthly_rent"),duplicate?"SKIPPED":"READY",duplicate?"Đã có hóa đơn trong kỳ":null);}).toList();}
 @Override @Transactional public BulkResult bulkGenerate(AuthenticatedUser p,BulkInvoice r){write(p);property(p,r.propertyId());List<CreateResult> created=new ArrayList<>();List<BulkPreviewRow> skipped=new ArrayList<>();LocalDate period=LocalDate.parse(r.billingPeriod()+"-01");for(Map<String,Object>x:repo.roomsForBulk(r.propertyId())){long room=l(x,"id");if(r.roomIds()!=null&&!r.roomIds().isEmpty()&&!r.roomIds().contains(room))continue;if(repo.duplicate(l(x,"contract_id"),period,null)){skipped.add(new BulkPreviewRow(room,s(x,"code"),s(x,"tenant_name"),money(x,"monthly_rent"),"SKIPPED","Đã có hóa đơn trong kỳ"));continue;}SaveInvoice req=new SaveInvoice(room,l(x,"contract_id"),r.billingPeriod(),period,period.withDayOfMonth(period.lengthOfMonth()),r.issueDate(),r.dueDate(),List.of(),BigDecimal.ZERO,true,null,r.action()==null?"SAVE_DRAFT":r.action(),null);created.add(createCalculated(p,req,x,period,true));}return new BulkResult(created,skipped);}
 @Override @Transactional public InvoiceDetail issue(AuthenticatedUser p,long id,long version){Map<String,Object>i=accessible(p,id,true);write(p);if(repo.issue(id,p.id(),version)==0)throw conflict();repo.history(id,"ISSUED",s(i,"status"),"ISSUED",null,p.id());return detail(p,id);}
 @Override @Transactional public InvoiceDetail payment(AuthenticatedUser p,long id,RecordPayment r){Map<String,Object>i=accessible(p,id,true);write(p);if(r.amount().compareTo(money(i,"remaining_amount"))>0)throw bad("PAYMENT_EXCEEDS_DEBT","Số tiền thanh toán vượt quá công nợ.");long version=r.version()==null?l(i,"version"):r.version();if(repo.applyPayment(id,r.amount(),version)==0)throw conflict();repo.payment(id,r.amount(),r.paymentMethod(),r.paidAt(),r.referenceCode(),r.note(),p.id());repo.history(id,"PAYMENT_RECORDED",s(i,"status"),r.amount().compareTo(money(i,"remaining_amount"))==0?"PAID":"PARTIALLY_PAID",null,p.id());return detail(p,id);}
 @Override @Transactional public InvoiceDetail cancel(AuthenticatedUser p,long id,CancelInvoice r){Map<String,Object>i=accessible(p,id,true);write(p);long v=r.version()==null?l(i,"version"):r.version();if(repo.cancel(id,r.reason(),p.id(),v)==0)throw bad("INVOICE_CANNOT_CANCEL","Không thể hủy hóa đơn đã thanh toán hoặc dữ liệu đã thay đổi.");repo.history(id,"CANCELLED",s(i,"status"),"CANCELLED",r.reason(),p.id());return detail(p,id);}
 @Override @Transactional public InvoiceDetail adjust(AuthenticatedUser p,long id,Adjustment r){Map<String,Object>i=accessible(p,id,true);write(p);long v=r.version()==null?l(i,"version"):r.version();if(repo.adjust(id,r.adjustmentType(),r.amount(),r.reason(),p.id(),v)==0)throw bad("ADJUSTMENT_INVALID","Khoản điều chỉnh không hợp lệ hoặc dữ liệu đã thay đổi.");repo.history(id,"ADJUSTED",s(i,"status"),s(i,"status"),r.reason(),p.id());return detail(p,id);}
 @Override @Transactional public InvoiceDetail reminder(AuthenticatedUser p,long id,Reminder r){Map<String,Object>i=accessible(p,id,false);write(p);String recipient="EMAIL".equals(r.channel())?s(i,"tenant_email"):s(i,"tenant_phone");if(recipient==null||recipient.isBlank())throw bad("REMINDER_RECIPIENT_MISSING","Người thuê chưa có thông tin nhận thông báo.");repo.reminder(id,r.channel(),recipient,p.id());repo.history(id,"REMINDER_SENT",s(i,"status"),s(i,"status"),r.channel(),p.id());return detail(p,id);}
 @Override @Transactional(readOnly=true) public byte[] export(AuthenticatedUser p,Long propertyId,String period,String status){StringBuilder out=new StringBuilder("\uFEFFMã hóa đơn,Kỳ,Nhà trọ,Phòng,Người thuê,Tổng tiền,Đã thu,Còn lại,Trạng thái\n");for(InvoiceRow r:list(p,propertyId,null,null,null,null,period,status,null,null,null,"newest",0,100).content())out.append(csv(r.invoiceCode())).append(',').append(csv(r.billingPeriod())).append(',').append(csv(r.property().name())).append(',').append(csv(r.room().name())).append(',').append(csv(r.tenant().name())).append(',').append(r.totalAmount()).append(',').append(r.paidAmount()).append(',').append(r.remainingAmount()).append(',').append(r.status()).append('\n');return out.toString().getBytes(StandardCharsets.UTF_8);}
 @Override @Transactional(readOnly=true) public byte[] pdf(AuthenticatedUser p,long id){InvoiceDetail d=detail(p,id);String text="INVOICE "+d.invoiceCode()+" | Room "+d.room().name()+" | Total "+d.totalAmount()+" VND | Paid "+d.paidAmount()+" | Remaining "+d.remainingAmount();return minimalPdf(text);}
 private Map<String,Object> accessible(AuthenticatedUser p,long id,boolean lock){read(p);Map<String,Object>i=repo.invoice(id,lock).orElseThrow(()->new AuthException(HttpStatus.NOT_FOUND,"INVOICE_NOT_FOUND","Không tìm thấy hóa đơn."));property(p,l(i,"property_id"));return i;}
 private void validateDates(SaveInvoice r){if(r.periodEndDate().isBefore(r.periodStartDate()))throw bad("INVOICE_PERIOD_INVALID","Ngày kết thúc kỳ phải sau ngày bắt đầu.");if(r.dueDate().isBefore(r.issueDate()==null?LocalDate.now():r.issueDate()))throw bad("INVOICE_DUE_DATE_INVALID","Hạn thanh toán không được trước ngày lập.");}
 private void read(AuthenticatedUser p){if(p==null||!List.of(RoleCode.OWNER,RoleCode.MANAGER,RoleCode.ACCOUNTANT).contains(p.activeRole()))throw new AuthException(HttpStatus.FORBIDDEN,"INVOICE_ACCESS_DENIED","Bạn không có quyền truy cập hóa đơn quản trị.");}private void write(AuthenticatedUser p){read(p);if(!canWrite(p))throw new AuthException(HttpStatus.FORBIDDEN,"INVOICE_WRITE_DENIED","Bạn không có quyền thay đổi hóa đơn.");}private boolean canWrite(AuthenticatedUser p){return List.of(RoleCode.OWNER,RoleCode.MANAGER,RoleCode.ACCOUNTANT).contains(p.activeRole());}private void property(AuthenticatedUser p,long id){if(!repo.canAccess(p.id(),p.activeRole(),id))throw new AuthException(HttpStatus.FORBIDDEN,"INVOICE_PROPERTY_DENIED","Bạn không có quyền với khu trọ này.");}
 private String effective(Map<String,Object>i){String st=s(i,"status");return !"CANCELLED".equals(st)&&!"PAID".equals(st)&&!"DRAFT".equals(st)&&money(i,"remaining_amount").signum()>0&&date(i,"due_date").isBefore(LocalDate.now())?"OVERDUE":st;}private AuthException bad(String c,String m){return new AuthException(HttpStatus.BAD_REQUEST,c,m);}private AuthException conflict(){return new AuthException(HttpStatus.CONFLICT,"INVOICE_VERSION_CONFLICT","Hóa đơn đã được người khác cập nhật. Vui lòng tải lại.");}
 private record CalcItem(String type,String name,String description,BigDecimal quantity,String unit,BigDecimal price,BigDecimal amount,String source,Long sourceId){}
 private static String s(Map<String,Object>m,String k){return m.get(k)==null?null:m.get(k).toString();}private static long l(Map<String,Object>m,String k){return ((Number)m.get(k)).longValue();}private static BigDecimal money(Map<String,Object>m,String k){Object x=m.get(k);return x==null?BigDecimal.ZERO:(BigDecimal)x;}private static BigDecimal nvl(BigDecimal x){return x==null?BigDecimal.ZERO:x;}private static LocalDate date(Map<String,Object>m,String k){Object x=m.get(k);if(x==null)return null;if(x instanceof LocalDate d)return d;if(x instanceof Date d)return d.toLocalDate();return ((Timestamp)x).toLocalDateTime().toLocalDate();}private static String period(LocalDate x){return "%02d/%d".formatted(x.getMonthValue(),x.getYear());}private static String csv(String x){return x==null?"":"\""+x.replace("\"","\"\"")+"\"";}
 private static byte[] minimalPdf(String value){String safe=value.replaceAll("[^\\x20-\\x7E]","?").replace("(","[").replace(")","]");String stream="BT /F1 12 Tf 50 760 Td ("+safe+") Tj ET";String[]o={"1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n","2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj\n","3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>endobj\n","4 0 obj<< /Length "+stream.length()+" >>stream\n"+stream+"\nendstream endobj\n","5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj\n"};StringBuilder b=new StringBuilder("%PDF-1.4\n");int[]pos=new int[6];for(int i=0;i<o.length;i++){pos[i+1]=b.length();b.append(o[i]);}int x=b.length();b.append("xref\n0 6\n0000000000 65535 f \n");for(int i=1;i<=5;i++)b.append(String.format("%010d 00000 n \n",pos[i]));b.append("trailer<< /Size 6 /Root 1 0 R >>\nstartxref\n").append(x).append("\n%%EOF");return b.toString().getBytes(StandardCharsets.US_ASCII);}
}
