package com.thangit.boardinghouse.service.impl;

import static com.thangit.boardinghouse.dto.response.maintenance.TechnicianResponses.*;
import com.thangit.boardinghouse.common.exception.AuthException;
import com.thangit.boardinghouse.domain.auth.RoleCode;
import com.thangit.boardinghouse.dto.request.maintenance.TechnicianRequests.*;
import com.thangit.boardinghouse.dto.request.maintenance.TechnicianRequests.Checklist;
import com.thangit.boardinghouse.dto.request.maintenance.TechnicianRequests.Diagnosis;
import com.thangit.boardinghouse.dto.request.maintenance.TechnicianRequests.WorkLog;
import com.thangit.boardinghouse.repository.TechnicianPortalRepository;
import com.thangit.boardinghouse.security.AuthenticatedUser;
import com.thangit.boardinghouse.service.TechnicianPortalService;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class TechnicianPortalServiceImpl implements TechnicianPortalService {
    private final TechnicianPortalRepository repository;
    private final PasswordEncoder passwordEncoder;
    private final boolean aiAvailable;
    public TechnicianPortalServiceImpl(TechnicianPortalRepository repository,PasswordEncoder passwordEncoder,
            @Value("${app.ai.provider:none}") String aiProvider){this.repository=repository;this.passwordEncoder=passwordEncoder;this.aiAvailable=aiProvider!=null&&!aiProvider.equalsIgnoreCase("none")&&!aiProvider.isBlank();}

    @Override @Transactional(readOnly=true) public Dashboard dashboard(AuthenticatedUser p){tech(p);Technician t=repository.technician(p.id()).orElseThrow(()->notFound("TECHNICIAN_PROFILE_NOT_FOUND","Không tìm thấy hồ sơ kỹ thuật viên."));Summary s=repository.summary(p.id());TaskRow current=repository.highlighted(p.id(),"CURRENT",1).stream().findFirst().orElse(null);List<TaskRow> next=repository.highlighted(p.id(),"NEXT",5),urgent=repository.highlighted(p.id(),"URGENT",5);List<String> pending=new ArrayList<>();if(s.urgentTaskCount()>0)pending.add(s.urgentTaskCount()+" công việc khẩn cấp cần xử lý");if(s.waitingPartsTaskCount()>0)pending.add(s.waitingPartsTaskCount()+" công việc đang chờ vật tư");if(s.inspectionPendingCount()>0)pending.add(s.inspectionPendingCount()+" công việc đang chờ nghiệm thu");return new Dashboard(t,s,current,next,urgent,pending,repository.notifications(p.id()).stream().limit(5).toList(),aiAvailable);}
    @Override @Transactional(readOnly=true) public Page<TaskRow> tasks(AuthenticatedUser p,String keyword,String status,String priority,String category,Long propertyId,LocalDate from,LocalDate to,Boolean overdue,String taskType,int page,int size,String sort){tech(p);if(page<0||size<1||size>100)throw bad("PAGE_INVALID","Thông tin phân trang không hợp lệ.");return repository.tasks(p.id(),keyword,status,priority,category,propertyId,from,to,overdue,taskType,page,size,sort);}
    @Override @Transactional(readOnly=true) public TaskDetail detail(AuthenticatedUser p,long id){tech(p);Map<String,Object> m=assigned(p,id,false);TaskRow row=repository.taskRow(p.id(),id).orElseThrow();Contact contact=new Contact(s(m,"tenant_name"),s(m,"contact_phone")!=null?s(m,"contact_phone"):s(m,"tenant_phone"),s(m,"preferred_time_slot"),bool(m,"tenant_presence_required"),s(m,"access_note"),bool(m,"pets_present"));return new TaskDetail(row,s(m,"description"),bool(m,"safety_risk"),contact,repository.schedule(id).orElse(null),repository.diagnosis(id).orElse(null),repository.checklist(id),repository.logs(id),repository.usages(id),repository.costs(id),repository.attachments(id),repository.messages(id),repository.inspection(id).orElse(null),repository.history(id),row.permissions());}

    @Override @Transactional public ActionResult accept(AuthenticatedUser p,long id,Versioned r){return transition(p,id,r.version(),List.of("ASSIGNED","NEW_ASSIGNMENT"),"ACCEPTED","ACCEPTED","Đã tiếp nhận công việc.");}
    @Override @Transactional public ActionResult decline(AuthenticatedUser p,long id,Reason r){tech(p);Map<String,Object> m=assigned(p,id,true);changed(repository.decline(p.id(),id,r.version(),r.reason().trim()));audit(id,p,"DECLINED",s(m,"status"),"DECLINED","Kỹ thuật viên từ chối công việc: "+r.reason());repository.notifyManagers(id,"Kỹ thuật viên từ chối công việc",s(m,"code")+" cần được phân công lại.","MAINTENANCE");return result(p,id,"Đã gửi lý do từ chối.");}
    @Override @Transactional public ActionResult startTravel(AuthenticatedUser p,long id,Versioned r){return transition(p,id,r.version(),List.of("ACCEPTED","SCHEDULED"),"TRAVELING","TRAVEL_STARTED","Đã bắt đầu di chuyển.");}
    @Override @Transactional public ActionResult checkIn(AuthenticatedUser p,long id,CheckIn r){tech(p);Map<String,Object> m=assigned(p,id,true);changed(repository.checkIn(p.id(),id,r.version(),r.checkedInAt(),r.note()));audit(id,p,"CHECKED_IN",s(m,"status"),"ARRIVED","Đã xác nhận có mặt tại địa điểm.");return result(p,id,"Đã xác nhận có mặt.");}
    @Override @Transactional public ActionResult start(AuthenticatedUser p,long id,Versioned r){return transition(p,id,r.version(),List.of("ARRIVED","ACCEPTED","SCHEDULED"),"IN_PROGRESS","STARTED","Đã bắt đầu xử lý.");}
    @Override @Transactional public ActionResult pause(AuthenticatedUser p,long id,Reason r){tech(p);Map<String,Object> m=assigned(p,id,true);String next=switch(r.reason()){case "WAITING_PARTS"->"WAITING_PARTS";case "WAITING_TENANT"->"WAITING_TENANT";case "WAITING_APPROVAL"->"WAITING_APPROVAL";default->"PAUSED";};changed(repository.pause(p.id(),id,r.version(),next,r.reason()+optional(r.note())));audit(id,p,"PAUSED",s(m,"status"),next,"Tạm dừng: "+r.reason()+optional(r.note()));return result(p,id,"Đã tạm dừng công việc.");}
    @Override @Transactional public ActionResult resume(AuthenticatedUser p,long id,Versioned r){return transition(p,id,r.version(),List.of("PAUSED","WAITING_PARTS","WAITING_TENANT","WAITING_APPROVAL"),"IN_PROGRESS","RESUMED","Đã tiếp tục xử lý.");}
    @Override @Transactional public ActionResult workLog(AuthenticatedUser p,long id,WorkLog r){tech(p);Map<String,Object> m=assigned(p,id,true);if(!"IN_PROGRESS".equals(s(m,"status")))throw conflict("TASK_NOT_IN_PROGRESS","Chỉ ghi nhật ký khi công việc đang xử lý.");changed(repository.bump(p.id(),id,r.version()));repository.addWorkLog(id,p.id(),r);audit(id,p,"WORK_LOG","IN_PROGRESS","IN_PROGRESS","Cập nhật tiến độ "+r.progressPercent()+"%: "+r.description());return result(p,id,"Đã lưu nhật ký công việc.");}
    @Override @Transactional public ActionResult diagnosis(AuthenticatedUser p,long id,Diagnosis r){tech(p);Map<String,Object> m=assigned(p,id,true);if(!TechnicianPortalRepository.permissions(s(m,"status")).canAddDiagnosis())throw conflict("DIAGNOSIS_NOT_ALLOWED","Trạng thái hiện tại không cho phép cập nhật chẩn đoán.");changed(repository.bump(p.id(),id,r.version()));repository.saveDiagnosis(id,p.id(),r);audit(id,p,"DIAGNOSIS_UPDATED",s(m,"status"),s(m,"status"),"Đã cập nhật chẩn đoán kỹ thuật.");if(r.safetyRisk())repository.notifyManagers(id,"Cảnh báo rủi ro an toàn",s(m,"code")+" được kỹ thuật viên đánh dấu có rủi ro.","URGENT");return result(p,id,"Đã lưu chẩn đoán.");}
    @Override @Transactional public ActionResult checklist(AuthenticatedUser p,long id,Checklist r){tech(p);Map<String,Object> m=assigned(p,id,true);changed(repository.bump(p.id(),id,r.version()));r.items().forEach(x->repository.updateChecklist(id,p.id(),x));audit(id,p,"CHECKLIST_UPDATED",s(m,"status"),s(m,"status"),"Đã cập nhật checklist kỹ thuật.");return result(p,id,"Đã cập nhật checklist.");}
    @Override @Transactional public ActionResult materialRequest(AuthenticatedUser p,long id,MaterialRequest r){tech(p);Map<String,Object> m=assigned(p,id,true);changed(repository.bump(p.id(),id,r.version()));repository.createMaterialRequest(id,p.id(),r);audit(id,p,"MATERIAL_REQUESTED",s(m,"status"),s(m,"status"),"Đã gửi yêu cầu vật tư.");repository.notifyManagers(id,"Yêu cầu vật tư mới",s(m,"code")+" có yêu cầu vật tư chờ duyệt.","MATERIAL");return result(p,id,"Đã gửi yêu cầu vật tư.");}
    @Override @Transactional public ActionResult materialUsage(AuthenticatedUser p,long id,MaterialUsage r){tech(p);Map<String,Object> m=assigned(p,id,true);changed(repository.bump(p.id(),id,r.version()));repository.addUsage(id,p.id(),r);audit(id,p,"MATERIAL_USED",s(m,"status"),s(m,"status"),"Đã ghi nhận vật tư sử dụng.");return result(p,id,"Đã ghi nhận vật tư sử dụng.");}
    @Override @Transactional public ActionResult cost(AuthenticatedUser p,long id,CostProposal r){tech(p);Map<String,Object> m=assigned(p,id,true);changed(repository.bump(p.id(),id,r.version()));repository.cost(id,p.id(),r);audit(id,p,"COST_SUBMITTED",s(m,"status"),"WAITING_APPROVAL","Đã gửi đề xuất chi phí chờ phê duyệt.");repository.notifyManagers(id,"Đề xuất chi phí chờ duyệt",s(m,"code")+" có đề xuất chi phí mới.","COST");return result(p,id,"Đã gửi đề xuất chi phí; kỹ thuật viên không tự phê duyệt.");}
    @Override @Transactional public ActionResult complete(AuthenticatedUser p,long id,Complete r){tech(p);Map<String,Object> m=assigned(p,id,true);if(!"IN_PROGRESS".equals(s(m,"status")))throw conflict("COMPLETE_NOT_ALLOWED","Công việc phải ở trạng thái đang xử lý.");if(repository.diagnosis(id).isEmpty())throw bad("DIAGNOSIS_REQUIRED","Cần hoàn tất chẩn đoán trước khi báo hoàn thành.");if(repository.countLogs(id)==0)throw bad("WORK_LOG_REQUIRED","Cần ít nhất một nhật ký công việc.");if(repository.incompleteRequiredChecklist(id)>0)throw bad("CHECKLIST_REQUIRED","Cần hoàn tất toàn bộ checklist bắt buộc.");if(repository.countAfterAttachments(id)==0)throw bad("RESULT_ATTACHMENT_REQUIRED","Cần ít nhất một ảnh kết quả sau sửa chữa.");repository.complete(id,r);Map<String,Object> updated=repository.taskData(p.id(),id,false).orElseThrow();if(((Number)updated.get("version")).longValue()==r.version())throw conflict("TASK_VERSION_CONFLICT","Công việc đã thay đổi, vui lòng tải lại.");audit(id,p,"COMPLETED","IN_PROGRESS","INSPECTION_PENDING","Kỹ thuật viên báo hoàn thành, đang chờ nghiệm thu.");repository.notifyManagers(id,"Công việc chờ nghiệm thu",s(m,"code")+" đã được kỹ thuật viên báo hoàn thành.","INSPECTION");return result(p,id,"Đã báo hoàn thành và chuyển sang chờ nghiệm thu.");}
    @Override @Transactional public ActionResult reschedule(AuthenticatedUser p,long id,Reschedule r){tech(p);Map<String,Object> m=assigned(p,id,true);if(!r.proposedStart().isAfter(LocalDateTime.now()))throw bad("RESCHEDULE_TIME_INVALID","Lịch đề xuất phải ở tương lai.");changed(repository.bump(p.id(),id,r.version()));repository.reschedule(id,p.id(),r);audit(id,p,"RESCHEDULE_REQUESTED",s(m,"status"),s(m,"status"),"Đã gửi yêu cầu đổi lịch.");repository.notifyManagers(id,"Yêu cầu đổi lịch",s(m,"code")+" có yêu cầu đổi lịch xử lý.","SCHEDULE");return result(p,id,"Đã gửi yêu cầu đổi lịch.");}
    @Override @Transactional public ActionResult transfer(AuthenticatedUser p,long id,Reason r){tech(p);Map<String,Object> m=assigned(p,id,true);changed(repository.bump(p.id(),id,r.version()));repository.transfer(id,p.id(),r.reason().trim());audit(id,p,"TRANSFER_REQUESTED",s(m,"status"),s(m,"status"),"Đã gửi yêu cầu chuyển công việc.");repository.notifyManagers(id,"Yêu cầu chuyển công việc",s(m,"code")+" cần quản lý xem xét.","MAINTENANCE");return result(p,id,"Đã gửi yêu cầu chuyển công việc.");}
    @Override @Transactional public ActionResult message(AuthenticatedUser p,long id,Message r){tech(p);Map<String,Object> m=assigned(p,id,true);repository.message(id,p.id(),r);audit(id,p,"MESSAGE_SENT",s(m,"status"),s(m,"status"),r.internal()?"Đã thêm trao đổi nội bộ.":"Đã gửi tin nhắn công việc.");return result(p,id,"Đã gửi tin nhắn.");}
    @Override @Transactional public Attachment upload(AuthenticatedUser p,long id,long version,String type,String caption,String name,String declaredMime,byte[] content){tech(p);Map<String,Object> m=assigned(p,id,true);if(!List.of("BEFORE","DURING","AFTER","RESULT","DOCUMENT").contains(type))throw bad("ATTACHMENT_TYPE_INVALID","Nhóm tệp không hợp lệ.");if(content==null||content.length==0||content.length>10*1024*1024)throw bad("ATTACHMENT_SIZE_INVALID","Tệp phải có dung lượng từ 1 byte đến 10 MB.");String mime=detect(content);if(mime==null||!mime.equals(declaredMime))throw bad("ATTACHMENT_MIME_INVALID","Nội dung tệp không khớp định dạng ảnh JPEG, PNG hoặc WebP được hỗ trợ.");changed(repository.bump(p.id(),id,version));long attachmentId=repository.attachment(id,p.id(),type,safeName(name),mime,content,caption);audit(id,p,"ATTACHMENT_ADDED",s(m,"status"),s(m,"status"),"Đã thêm ảnh "+type+".");return repository.attachments(id).stream().filter(x->x.id()==attachmentId).findFirst().orElseThrow();}
    @Override @Transactional(readOnly=true) public FileData attachment(AuthenticatedUser p,long id,long attachmentId){tech(p);return repository.attachmentFile(id,attachmentId,p.id()).orElseThrow(()->notFound("ATTACHMENT_NOT_FOUND","Không tìm thấy tệp đính kèm."));}
    @Override @Transactional(readOnly=true) public List<CalendarItem> calendar(AuthenticatedUser p,LocalDate from,LocalDate to){tech(p);LocalDate start=from==null?LocalDate.now().withDayOfMonth(1):from,end=to==null?start.plusMonths(1).minusDays(1):to;if(end.isBefore(start)||Duration.between(start.atStartOfDay(),end.plusDays(1).atStartOfDay()).toDays()>366)throw bad("CALENDAR_RANGE_INVALID","Khoảng lịch không hợp lệ.");return repository.calendar(p.id(),start,end);}
    @Override @Transactional(readOnly=true) public List<PreventivePlan> plans(AuthenticatedUser p){tech(p);return repository.plans(p.id());}
    @Override @Transactional(readOnly=true) public List<Asset> assets(AuthenticatedUser p){tech(p);return repository.assets(p.id());}
    @Override @Transactional(readOnly=true) public Asset asset(AuthenticatedUser p,long id){tech(p);return repository.asset(p.id(),id).orElseThrow(()->notFound("ASSET_NOT_FOUND","Không tìm thấy thiết bị trong phạm vi công việc được giao."));}
    @Override @Transactional(readOnly=true) public List<MaterialCatalog> materials(AuthenticatedUser p){tech(p);return repository.materials(p.id());}
    @Override @Transactional(readOnly=true) public List<MaterialRequestRow> materialRequests(AuthenticatedUser p){tech(p);return repository.materialRequests(p.id());}
    @Override @Transactional public void receiveMaterial(AuthenticatedUser p,long id,long version){tech(p);changed(repository.receiveMaterialRequest(p.id(),id,version));}
    @Override @Transactional(readOnly=true) public List<Notification> notifications(AuthenticatedUser p){tech(p);return repository.notifications(p.id());}
    @Override @Transactional public void markRead(AuthenticatedUser p,long id){tech(p);if(repository.markRead(p.id(),id)==0)throw notFound("NOTIFICATION_NOT_FOUND","Không tìm thấy thông báo.");}
    @Override @Transactional(readOnly=true) public Performance performance(AuthenticatedUser p){tech(p);return repository.performance(p.id());}
    @Override @Transactional(readOnly=true) public Account account(AuthenticatedUser p){tech(p);return repository.account(p.id());}
    @Override @Transactional public Account profile(AuthenticatedUser p,ProfileUpdate r){tech(p);if(r.email()==null||r.email().isBlank())throw bad("EMAIL_REQUIRED","Email không được để trống.");if(repository.emailExists(p.id(),r.email()))throw conflict("EMAIL_EXISTS","Email đã được sử dụng.");changed(repository.updateProfile(p.id(),r));return repository.account(p.id());}
    @Override @Transactional public Account preferences(AuthenticatedUser p,PreferenceUpdate r){tech(p);changed(repository.updatePreferences(p.id(),r));return repository.account(p.id());}
    @Override @Transactional public void password(AuthenticatedUser p,PasswordChange r){tech(p);String current=repository.passwordHash(p.id()).orElseThrow();if(!passwordEncoder.matches(r.currentPassword(),current))throw bad("CURRENT_PASSWORD_INVALID","Mật khẩu hiện tại không đúng.");if(passwordEncoder.matches(r.newPassword(),current))throw bad("PASSWORD_UNCHANGED","Mật khẩu mới phải khác mật khẩu hiện tại.");repository.changePassword(p.id(),passwordEncoder.encode(r.newPassword()));}
    @Override @Transactional public void revokeSession(AuthenticatedUser p,long id){tech(p);if(repository.revokeSession(p.id(),id)==0)throw notFound("SESSION_NOT_FOUND","Không tìm thấy phiên đăng nhập đang hoạt động.");}

    private ActionResult transition(AuthenticatedUser p,long id,long version,List<String> from,String to,String action,String description){tech(p);Map<String,Object> m=assigned(p,id,true);changed(repository.transition(p.id(),id,version,from,to,description));audit(id,p,action,s(m,"status"),to,description);return result(p,id,description);}
    private ActionResult result(AuthenticatedUser p,long id,String message){TaskRow row=repository.taskRow(p.id(),id).orElseThrow();return new ActionResult(id,row.status(),row.version(),message);}
    private Map<String,Object> assigned(AuthenticatedUser p,long id,boolean lock){return repository.taskData(p.id(),id,lock).orElseThrow(()->notFound("TECHNICIAN_TASK_NOT_FOUND","Không tìm thấy công việc hoặc công việc không được giao cho bạn."));}
    private void tech(AuthenticatedUser p){if(p==null||p.activeRole()!=RoleCode.TECHNICIAN)throw new AuthException(HttpStatus.FORBIDDEN,"TECHNICIAN_ACCESS_DENIED","Chỉ tài khoản kỹ thuật viên được truy cập cổng này.");}
    private void changed(int n){if(n==0)throw conflict("TASK_VERSION_CONFLICT","Công việc đã thay đổi hoặc trạng thái không cho phép. Vui lòng tải lại.");}
    private void audit(long id,AuthenticatedUser p,String action,String before,String after,String text){repository.history(id,p.id(),action,before,after,text);}
    private static String detect(byte[] b){if(b.length>=3&&(b[0]&255)==0xff&&(b[1]&255)==0xd8&&(b[2]&255)==0xff)return "image/jpeg";if(b.length>=8&&(b[0]&255)==0x89&&b[1]==0x50&&b[2]==0x4e&&b[3]==0x47)return "image/png";if(b.length>=12&&new String(b,0,4).equals("RIFF")&&new String(b,8,4).equals("WEBP"))return "image/webp";return null;}
    private static String safeName(String x){String n=x==null?"attachment":x.replaceAll("[\\r\\n\\\\/]","_");return n.length()>180?n.substring(n.length()-180):n;}
    private static String s(Map<String,Object> m,String k){Object x=m.get(k);return x==null?null:x.toString();}
    private static boolean bool(Map<String,Object>m,String k){Object x=m.get(k);return x!=null&&((x instanceof Boolean b&&b)||(x instanceof Number n&&n.intValue()!=0));}
    private static String optional(String x){return x==null||x.isBlank()?"":" — "+x.trim();}
    private AuthException bad(String code,String text){return new AuthException(HttpStatus.BAD_REQUEST,code,text);}
    private AuthException conflict(String code,String text){return new AuthException(HttpStatus.CONFLICT,code,text);}
    private AuthException notFound(String code,String text){return new AuthException(HttpStatus.NOT_FOUND,code,text);}
}
