package com.thangit.boardinghouse.service.impl;

import static com.thangit.boardinghouse.dto.request.occupant.TenantCoOccupantRequests.*;
import static com.thangit.boardinghouse.dto.response.occupant.TenantCoOccupantResponses.*;
import com.thangit.boardinghouse.common.exception.AuthException;
import com.thangit.boardinghouse.domain.auth.RoleCode;
import com.thangit.boardinghouse.repository.TenantCoOccupantRepository;
import com.thangit.boardinghouse.repository.TenantCoOccupantRepository.ActiveContext;
import com.thangit.boardinghouse.repository.TenantCoOccupantRepository.RequestBase;
import com.thangit.boardinghouse.security.AuthenticatedUser;
import com.thangit.boardinghouse.service.TenantCoOccupantService;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

@Service
public class TenantCoOccupantServiceImpl implements TenantCoOccupantService {
    private static final Set<String> REQUEST_STATUSES=Set.of("SUBMITTED","UNDER_REVIEW","NEED_MORE_INFORMATION","APPROVED","REJECTED","CANCELLED","COMPLETED");
    private static final Set<String> DOCUMENT_TYPES=Set.of("CITIZEN_ID_FRONT","CITIZEN_ID_BACK","PASSPORT","BIRTH_CERTIFICATE","TEMPORARY_RESIDENCE","OTHER");
    private final TenantCoOccupantRepository repository;
    public TenantCoOccupantServiceImpl(TenantCoOccupantRepository repository){this.repository=repository;}

    @Override @Transactional(readOnly=true) public Overview overview(AuthenticatedUser p){ActiveContext c=context(p);int available=Math.max(0,c.capacity()-c.occupantCount());String cap=c.occupantCount()>c.capacity()?"OVER_CAPACITY":available==0?"FULL":"AVAILABLE";boolean active=c.contractId()!=null&&c.endDate()!=null&&Set.of("ACTIVE","EXPIRING").contains(c.contractStatus())&&!c.endDate().isBefore(LocalDate.now());boolean representative="REPRESENTATIVE".equals(c.role());String reason=!representative?"Chỉ người đại diện thuê được gửi yêu cầu đăng ký người ở cùng.":!active?"Bạn chưa có hợp đồng thuê còn hiệu lực cho phòng này.":available==0?"Phòng đã đạt số người tối đa.":null;return new Overview(new RoomInfo(c.roomId(),c.propertyName(),c.address(),c.buildingName(),c.floorName(),c.roomCode(),c.roomType(),c.area(),c.occupantCount(),c.capacity(),available,cap,c.roomStatus()),new ContractInfo(c.contractId(),c.contractCode(),c.endDate(),c.contractStatus(),c.representativeName()),repository.summary(c),new OverviewPermissions(reason==null,representative,reason));}
    @Override @Transactional(readOnly=true) public Page<OccupantRow> occupants(AuthenticatedUser p,int page,int size){ActiveContext c=context(p);page(page,size);long total=repository.occupantCount(c.roomId());return new Page<>(repository.occupants(c,size,page*size),page,size,total,pages(total,size));}
    @Override @Transactional(readOnly=true) public OccupantDetail occupant(AuthenticatedUser p,long id){ActiveContext c=context(p);if(!"REPRESENTATIVE".equals(c.role())&&id!=c.profileId())throw forbidden("Bạn chỉ được xem hồ sơ chi tiết của chính mình.");return repository.occupant(c,id).orElseThrow(()->notFound("Không tìm thấy người đang cư trú."));}
    @Override @Transactional(readOnly=true) public Page<RequestRow> requests(AuthenticatedUser p,String status,int page,int size){ActiveContext c=context(p);requireRepresentative(c);page(page,size);String normalized=status==null||status.isBlank()?null:status.trim().toUpperCase();if(normalized!=null&&!REQUEST_STATUSES.contains(normalized))throw bad("Trạng thái yêu cầu không hợp lệ.");long total=repository.countRequests(c,normalized);return new Page<>(repository.requests(c,normalized,size,page*size),page,size,total,pages(total,size));}
    @Override @Transactional(readOnly=true) public Page<ResidencePeriod> history(AuthenticatedUser p,int page,int size){ActiveContext c=context(p);requireRepresentative(c);page(page,size);long total=repository.historyCount(c);return new Page<>(repository.roomHistory(c,size,page*size),page,size,total,pages(total,size));}

    @Override @Transactional public Created create(AuthenticatedUser p,String key,CreateRequest r){ActiveContext c=context(p);requireRepresentative(c);validateKey(key);RequestBase previous=repository.byIdempotency(p.id(),key).orElse(null);if(previous!=null)return new Created(previous.id(),previous.code(),previous.status());Overview overview=overview(p);if(!overview.permissions().canCreateOccupantRequest())throw new AuthException(HttpStatus.CONFLICT,"CO_OCCUPANT_NOT_ALLOWED",overview.permissions().createDisabledReason());validateCreate(c,r);if(repository.duplicate(c.roomId(),r.phone().trim(),r.identityDocument().number().trim()))throw new AuthException(HttpStatus.CONFLICT,"CO_OCCUPANT_DUPLICATE","Người này đã có hồ sơ hoặc yêu cầu đang được xử lý.");long id=repository.create(p.id(),c,key,r);RequestBase created=repository.request(c,id).orElseThrow();repository.addHistory(id,"SUBMITTED","Yêu cầu đăng ký người ở cùng đã được gửi.","Khách thuê");repository.notifyManagers(c,"Yêu cầu đăng ký người ở cùng",created.code()+" đang chờ kiểm tra.");return new Created(id,created.code(),created.status());}
    @Override @Transactional(readOnly=true) public RequestDetail request(AuthenticatedUser p,long id){ActiveContext c=context(p);RequestBase r=ownedRequest(p,c,id);String identity=r.identityNumber();String masked=identity==null?null:"********"+identity.substring(Math.max(0,identity.length()-4));return new RequestDetail(r.id(),r.code(),r.type(),r.status(),r.version(),r.submittedAt(),r.updatedAt(),new PersonInfo(r.fullName(),r.dateOfBirth(),r.gender(),maskPhone(r.phone()),maskEmail(r.email()),r.relationship(),r.occupation(),r.workplace(),masked,r.identityType()),new ResidenceInfo(c.propertyName(),c.roomCode(),r.moveIn(),r.moveOut(),r.reason(),r.note()),repository.documents(id),new TemporaryResidence("NOT_DECLARED",null,null,null,null),r.informationMessage()==null?null:new InformationRequest(r.informationMessage(),r.informationDeadline()),r.publicFeedback(),repository.history(id),TenantCoOccupantRepository.permissions(r.status()));}
    @Override @Transactional public Uploaded upload(AuthenticatedUser p,long id,String type,List<MultipartFile> files){ActiveContext c=context(p);RequestBase r=ownedRequest(p,c,id);if(!Set.of("SUBMITTED","NEED_MORE_INFORMATION").contains(r.status()))throw new AuthException(HttpStatus.CONFLICT,"REQUEST_NOT_EDITABLE","Yêu cầu hiện không cho phép tải thêm hồ sơ.");String normalized=type==null?"OTHER":type.trim().toUpperCase();if(!DOCUMENT_TYPES.contains(normalized))throw bad("Loại giấy tờ không hợp lệ.");if(files==null||files.isEmpty()||files.size()>5)throw bad("Vui lòng chọn từ 1 đến 5 tệp.");List<Long> ids=new ArrayList<>();for(MultipartFile file:files){byte[] bytes;try{bytes=file.getBytes();}catch(Exception e){throw bad("Không thể đọc tệp tải lên.");}String mime=detect(bytes);if(mime==null||bytes.length>5*1024*1024)throw bad("Chỉ chấp nhận JPG, PNG, WEBP hoặc PDF tối đa 5MB.");String name=safeName(file.getOriginalFilename());ids.add(repository.addDocument(id,p.id(),normalized,name,mime,bytes));}repository.addHistory(id,"DOCUMENT_ADDED","Khách thuê đã bổ sung hồ sơ.","Khách thuê");return new Uploaded(ids);}
    @Override @Transactional(readOnly=true) public FileData file(AuthenticatedUser p,long id){ActiveContext c=context(p);return repository.file(c,p.id(),id).orElseThrow(()->notFound("Không tìm thấy tài liệu hoặc bạn không có quyền tải tệp."));}
    @Override @Transactional public ActionResult additional(AuthenticatedUser p,long id,AdditionalInformation request){ActiveContext c=context(p);RequestBase r=ownedRequest(p,c,id);if(repository.additional(id,request.version(),p.id(),request.content().trim())==0)throw conflict();repository.addHistory(id,"INFORMATION_ADDED","Khách thuê đã gửi thông tin bổ sung.","Khách thuê");repository.notifyManagers(c,"Hồ sơ người ở cùng đã được bổ sung",r.code()+" đã có thông tin mới.");return new ActionResult(id,"SUBMITTED",request.version()+1);}
    @Override @Transactional public ActionResult cancel(AuthenticatedUser p,long id,CancelRequest request){ActiveContext c=context(p);RequestBase r=ownedRequest(p,c,id);if(repository.cancel(id,request.version(),request.reason().trim())==0)throw conflict();repository.addHistory(id,"CANCELLED","Khách thuê đã hủy yêu cầu: "+request.reason().trim(),"Khách thuê");return new ActionResult(id,"CANCELLED",request.version()+1);}
    @Override @Transactional public Created moveOut(AuthenticatedUser p,long occupantId,String key,MoveOutRequest request){ActiveContext c=context(p);requireRepresentative(c);validateKey(key);var occupant=repository.occupant(c,occupantId).orElseThrow(()->notFound("Không tìm thấy người ở cùng."));if("REPRESENTATIVE".equals(occupant.residenceRole()))throw bad("Không thể gửi yêu cầu chuyển đi cho người đại diện thuê.");RequestBase previous=repository.byIdempotency(p.id(),key).orElse(null);if(previous!=null)return new Created(previous.id(),previous.code(),previous.status());long id=repository.createMoveOut(p.id(),c,occupantId,occupant.fullName(),key,request.expectedMoveOutDate(),request.reason().trim(),request.note(),request.contactPhone().trim());RequestBase created=repository.request(c,id).orElseThrow();repository.addHistory(id,"SUBMITTED","Yêu cầu chuyển đi đã được gửi.","Khách thuê");repository.notifyManagers(c,"Yêu cầu người ở cùng chuyển đi",created.code()+" đang chờ xử lý.");return new Created(id,created.code(),created.status());}

    private ActiveContext context(AuthenticatedUser p){if(p==null||p.activeRole()!=RoleCode.TENANT)throw forbidden("Chỉ khách thuê được sử dụng chức năng này.");return repository.activeContext(p.id()).orElseThrow(()->notFound("Không tìm thấy phòng đang cư trú hợp lệ."));}
    private RequestBase ownedRequest(AuthenticatedUser p,ActiveContext c,long id){RequestBase r=repository.request(c,id).orElseThrow(()->repository.requestExists(id)?forbidden("Bạn không có quyền xem yêu cầu này."):notFound("Không tìm thấy yêu cầu."));if(!"REPRESENTATIVE".equals(c.role())&&r.requesterUserId()!=p.id())throw forbidden("Bạn không có quyền xem yêu cầu này.");return r;}
    private void requireRepresentative(ActiveContext c){if(!"REPRESENTATIVE".equals(c.role()))throw forbidden("Chỉ người đại diện thuê được thực hiện thao tác này.");}
    private void validateCreate(ActiveContext c,CreateRequest r){if(r.dateOfBirth().isAfter(LocalDate.now()))throw bad("Ngày sinh không được ở tương lai.");if(r.expectedMoveOutDate()!=null&&!r.expectedMoveOutDate().isAfter(r.expectedMoveInDate()))throw bad("Ngày chuyển đi phải sau ngày chuyển vào.");if(r.expectedMoveOutDate()!=null&&r.expectedMoveOutDate().isAfter(c.endDate()))throw bad("Ngày chuyển đi không được vượt ngày kết thúc hợp đồng.");if(!r.fullName().matches(".*[\\p{L}].*"))throw bad("Họ tên không hợp lệ.");}
    private void validateKey(String key){if(key==null||key.isBlank()||key.length()>100)throw bad("Idempotency-Key không hợp lệ.");}
    private void page(int page,int size){if(page<0||size<1||size>50)throw bad("Thông tin phân trang không hợp lệ.");}
    private int pages(long total,int size){return (int)Math.ceil((double)total/size);}
    private String detect(byte[] b){if(b.length>=4&&b[0]==(byte)0xFF&&b[1]==(byte)0xD8)return "image/jpeg";if(b.length>=8&&b[0]==(byte)0x89&&b[1]==0x50&&b[2]==0x4E&&b[3]==0x47)return "image/png";if(b.length>=12&&new String(b,0,4).equals("RIFF")&&new String(b,8,4).equals("WEBP"))return "image/webp";if(b.length>=5&&new String(b,0,5).equals("%PDF-"))return "application/pdf";return null;}
    private String safeName(String n){String v=n==null?"tai-lieu":n.replace('\\','/');v=v.substring(v.lastIndexOf('/')+1).replaceAll("[\\r\\n]","_");return v.length()>200?v.substring(v.length()-200):v;}
    private String maskPhone(String v){if(v==null||v.length()<7)return v;return v.substring(0,3)+"****"+v.substring(v.length()-3);}
    private String maskEmail(String v){if(v==null||!v.contains("@"))return null;return v.charAt(0)+"***"+v.substring(v.indexOf('@'));}
    private AuthException bad(String m){return new AuthException(HttpStatus.BAD_REQUEST,"CO_OCCUPANT_INVALID",m);}
    private AuthException forbidden(String m){return new AuthException(HttpStatus.FORBIDDEN,"CO_OCCUPANT_FORBIDDEN",m);}
    private AuthException notFound(String m){return new AuthException(HttpStatus.NOT_FOUND,"CO_OCCUPANT_NOT_FOUND",m);}
    private AuthException conflict(){return new AuthException(HttpStatus.CONFLICT,"CO_OCCUPANT_VERSION_CONFLICT","Thông tin đã được quản lý cập nhật. Vui lòng tải lại.");}
}
