package com.thangit.boardinghouse.service.impl;

import static com.thangit.boardinghouse.dto.response.maintenance.TenantMaintenanceResponses.*;
import com.thangit.boardinghouse.common.exception.AuthException;import com.thangit.boardinghouse.domain.auth.RoleCode;
import com.thangit.boardinghouse.dto.request.maintenance.TenantMaintenanceRequests.*;import com.thangit.boardinghouse.repository.TenantMaintenanceRepository;
import com.thangit.boardinghouse.security.AuthenticatedUser;import com.thangit.boardinghouse.service.TenantMaintenanceService;
import java.io.IOException;import java.nio.charset.StandardCharsets;import java.sql.Timestamp;import java.time.LocalDate;import java.time.LocalDateTime;
import java.util.List;import java.util.Map;import java.util.Set;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;

@Service
public class TenantMaintenanceServiceImpl implements TenantMaintenanceService{
 private static final Set<String> CATEGORIES=Set.of("ELECTRICAL","WATER","INTERNET","AIR_CONDITIONER","WATER_HEATER","DOOR_LOCK","FURNITURE","APPLIANCE","STRUCTURE","LEAKAGE","SANITATION","SECURITY","FIRE_SAFETY","COMMON_AREA","ELEVATOR","OTHER");
 private static final Set<String> PRIORITIES=Set.of("LOW","MEDIUM","HIGH","URGENT");private static final int MAX_FILES=5;
 private final TenantMaintenanceRepository repo;private final boolean aiAvailable;
 public TenantMaintenanceServiceImpl(TenantMaintenanceRepository repo,@Value("${app.ai.api-key:}")String aiKey,@Value("${app.ai.provider:none}")String provider){this.repo=repo;this.aiAvailable=aiKey!=null&&!aiKey.isBlank()&&provider!=null&&!provider.equalsIgnoreCase("none");}
 @Override@Transactional(readOnly=true)public Summary summary(AuthenticatedUser p){tenant(p);return repo.summary(p.id());}
 @Override@Transactional(readOnly=true)public List<AvailableLocation> locations(AuthenticatedUser p){tenant(p);return repo.locations(p.id());}
 @Override@Transactional(readOnly=true)public Page<RequestRow> list(AuthenticatedUser p,String status,String keyword,String category,String priority,Long roomId,LocalDate start,LocalDate end,String sort,int page,int size){tenant(p);if(page<0||size<1||size>100)throw bad("PAGINATION_INVALID","Thông tin phân trang không hợp lệ.");if(start!=null&&end!=null&&start.isAfter(end))throw bad("DATE_RANGE_INVALID","Khoảng ngày không hợp lệ.");if(category!=null&&!category.isBlank()&&!CATEGORIES.contains(category))throw bad("CATEGORY_INVALID","Loại sự cố không hợp lệ.");if(priority!=null&&!priority.isBlank()&&!PRIORITIES.contains(priority))throw bad("PRIORITY_INVALID","Mức độ ảnh hưởng không hợp lệ.");if(roomId!=null&&repo.activeLocation(p.id(),roomId).isEmpty())throw denied("Phòng không thuộc nơi cư trú hiện tại của bạn.");String statuses=statuses(status);String order=switch(sort==null?"newest":sort){case"oldest"->"m.created_at ASC";case"updated"->"m.updated_at DESC";case"priority"->"FIELD(COALESCE(m.reported_priority,m.priority),'URGENT','HIGH','MEDIUM','LOW'),m.created_at DESC";case"schedule"->"sch.scheduled_start IS NULL,sch.scheduled_start ASC";default->"m.created_at DESC";};return repo.list(p.id(),statuses,clean(keyword),clean(category),clean(priority),roomId,start,end,page,size,order);}
 @Override@Transactional public Detail detail(AuthenticatedUser p,long id){Map<String,Object>m=owned(p,id,false);return detailOf(p,m);}
 @Override@Transactional public Created create(AuthenticatedUser p,String key,CreateRequest r){tenant(p);if(key==null||key.isBlank()||key.length()>100)throw bad("IDEMPOTENCY_KEY_REQUIRED","Thiếu khóa chống gửi trùng hợp lệ.");Created old=repo.byIdempotency(p.id(),key.trim()).orElse(null);if(old!=null)return old;AvailableLocation loc=repo.activeLocation(p.id(),r.roomId()).orElseThrow(()->denied("Bạn chỉ có thể báo sự cố cho phòng đang thuê."));if(r.assetId()!=null&&!repo.assetInRoom(r.roomId(),r.assetId()))throw bad("ASSET_INVALID","Thiết bị không thuộc phòng đã chọn.");if(!CATEGORIES.contains(r.category())||!PRIORITIES.contains(r.reportedPriority()))throw bad("MAINTENANCE_CLASSIFICATION_INVALID","Loại sự cố hoặc mức độ ảnh hưởng không hợp lệ.");if(r.detectedAt().isAfter(LocalDateTime.now().plusMinutes(5)))throw bad("DETECTED_TIME_INVALID","Thời điểm phát hiện không được ở tương lai.");if(r.preferredSchedule().preferredDate().isBefore(LocalDate.now()))throw bad("PREFERRED_DATE_INVALID","Ngày mong muốn không được ở quá khứ.");if("URGENT".equals(r.reportedPriority())&&r.description().trim().length()<30)throw bad("URGENT_DESCRIPTION_REQUIRED","Vui lòng mô tả rõ nguy cơ đối với yêu cầu khẩn cấp.");if(repo.duplicateOpen(p.id(),r.roomId(),r.assetId(),r.category()))throw conflict("DUPLICATE_MAINTENANCE_REQUEST","Một yêu cầu tương tự đang được xử lý trong 24 giờ gần đây.");PreferredSchedule s=r.preferredSchedule();Created made=repo.create(p.id(),loc,r.assetId(),r.areaCode(),r.title().trim(),r.description().trim(),r.category(),r.reportedPriority(),r.detectedAt(),r.safetyRisk(),r.continuousIssue(),r.assetUsable(),s.preferredDate(),s.timeSlot(),s.tenantPresenceRequired(),s.accessPreference()==null?"TENANT_PRESENT":s.accessPreference(),r.contactPhone().trim(),join(r.note(),s.accessNote()),s.petsPresent(),key.trim());repo.history(made.id(),"SUBMITTED",null,"SUBMITTED","Khách thuê đã gửi yêu cầu sửa chữa",p.id());repo.notifyManagers(loc.location().propertyId(),"Yêu cầu sửa chữa mới",made.requestCode()+" · "+r.title().trim());return made;}
 @Override@Transactional public Uploaded upload(AuthenticatedUser p,long id,List<MultipartFile>files,String type,String caption){Map<String,Object>m=owned(p,id,true);if(!TenantMaintenanceRepository.permissions(str(m,"status"),repo.schedule(id)!=null).canUpload())throw bad("UPLOAD_NOT_ALLOWED","Không thể bổ sung tệp ở trạng thái hiện tại.");if(files==null||files.isEmpty())throw bad("ATTACHMENT_REQUIRED","Vui lòng chọn ít nhất một tệp.");if(files.size()+repo.attachmentCount(id)>MAX_FILES)throw bad("ATTACHMENT_LIMIT","Mỗi yêu cầu chỉ được tối đa 5 tệp.");for(MultipartFile f:files){byte[]bytes=bytes(f);String mime=detect(bytes);long limit="video/mp4".equals(mime)?20L*1024*1024:5L*1024*1024;if(mime==null||f.getSize()>limit)throw bad("ATTACHMENT_INVALID","Tệp không hợp lệ hoặc vượt quá dung lượng cho phép.");repo.addAttachment(id,p.id(),validAttachmentType(type),safe(f.getOriginalFilename()),mime,bytes,caption);}repo.history(id,"ATTACHMENT_ADDED",str(m,"status"),str(m,"status"),"Khách thuê đã bổ sung hình ảnh hoặc video",p.id());return new Uploaded(repo.attachments(id));}
 @Override@Transactional(readOnly=true)public FileData file(AuthenticatedUser p,long id){tenant(p);return repo.file(p.id(),id).orElseThrow(()->notFound("Không tìm thấy tệp hoặc bạn không có quyền tải tệp."));}
 @Override@Transactional public List<MessageItem> messages(AuthenticatedUser p,long id){owned(p,id,false);return repo.messages(id,p.id());}
 @Override@Transactional public MessageItem message(AuthenticatedUser p,long id,Message r){Map<String,Object>m=owned(p,id,true);if(!TenantMaintenanceRepository.permissions(str(m,"status"),repo.schedule(id)!=null).canSendMessage())throw bad("MESSAGE_NOT_ALLOWED","Yêu cầu đã đóng, không thể gửi thêm tin nhắn.");MessageItem x=repo.addMessage(id,p.id(),r.content().trim());repo.notifyManagers(longValue(m,"property_id"),"Tin nhắn sửa chữa mới",str(m,"code")+" có phản hồi từ khách thuê");return x;}
 @Override@Transactional public ActionResult additional(AuthenticatedUser p,long id,AdditionalInformation r){Map<String,Object>m=owned(p,id,true);changed(repo.additional(id,p.id(),r.content().trim(),r.contactPhone(),r.version(),str(m,"status")));String next="NEED_MORE_INFORMATION".equals(str(m,"status"))?"RECEIVED":str(m,"status");repo.history(id,"ADDITIONAL_INFORMATION",str(m,"status"),next,"Khách thuê đã bổ sung thông tin",p.id());repo.notifyManagers(longValue(m,"property_id"),"Thông tin sửa chữa được bổ sung",str(m,"code"));return result(p,id);}
 @Override@Transactional public ActionResult schedule(AuthenticatedUser p,long id,ScheduleResponse r){Map<String,Object>m=owned(p,id,true);Schedule s=repo.schedule(id);if(s==null)throw bad("SCHEDULE_NOT_FOUND","Yêu cầu chưa có lịch hẹn đang hiệu lực.");if("REQUEST_RESCHEDULE".equals(r.response())&&(r.preferredStart()==null||r.note()==null||r.note().isBlank()))throw bad("RESCHEDULE_DETAILS_REQUIRED","Vui lòng chọn thời gian mới và nhập lý do đổi lịch.");if(r.preferredStart()!=null&&r.preferredStart().isBefore(LocalDateTime.now()))throw bad("PREFERRED_TIME_INVALID","Thời gian mong muốn không được ở quá khứ.");changed(repo.scheduleResponse(id,s.id(),p.id(),r.response(),r.preferredStart(),r.note(),r.version()));String action="CONFIRMED".equals(r.response())?"SCHEDULE_CONFIRMED":"RESCHEDULE_REQUESTED";repo.history(id,action,str(m,"status"),str(m,"status"),"CONFIRMED".equals(r.response())?"Khách thuê đã xác nhận lịch":"Khách thuê đã yêu cầu đổi lịch",p.id());repo.notifyManagers(longValue(m,"property_id"),"Phản hồi lịch sửa chữa",str(m,"code"));return result(p,id);}
 @Override@Transactional public ActionResult cancel(AuthenticatedUser p,long id,Cancel r){Map<String,Object>m=owned(p,id,true);String reason=r.reason()+(r.note()==null||r.note().isBlank()?"":" · "+r.note().trim());changed(repo.cancel(id,r.version(),reason));repo.history(id,"CANCELLED",str(m,"status"),"CANCELLED","Khách thuê đã hủy yêu cầu: "+reason,p.id());repo.notifyManagers(longValue(m,"property_id"),"Yêu cầu sửa chữa đã hủy",str(m,"code"));return result(p,id);}
 @Override@Transactional public ActionResult feedback(AuthenticatedUser p,long id,Feedback r){Map<String,Object>m=owned(p,id,true);if(repo.hasFeedback(id,p.id()))throw conflict("FEEDBACK_ALREADY_EXISTS","Bạn đã đánh giá yêu cầu này.");if(!"PASSED".equals(r.result())&&(r.comment()==null||r.comment().trim().length()<10))throw bad("FEEDBACK_COMMENT_REQUIRED","Vui lòng mô tả vấn đề còn tồn tại.");changed(repo.feedback(id,p.id(),r.result(),r.rating(),r.staffAttitudeRating(),r.resolutionTimeRating(),r.comment(),r.assetWorking(),r.version()));String next="PASSED".equals(r.result())?"RESOLVED":"REOPENED";repo.history(id,"TENANT_FEEDBACK",str(m,"status"),next,"PASSED".equals(r.result())?"Khách thuê xác nhận đã hoàn thành":"Khách thuê báo kết quả chưa đạt",p.id());repo.notifyManagers(longValue(m,"property_id"),"Khách thuê đã nghiệm thu",str(m,"code"));return result(p,id);}
 @Override@Transactional public ActionResult reopen(AuthenticatedUser p,long id,Reopen r){Map<String,Object>m=owned(p,id,true);if(!PRIORITIES.contains(r.currentPriority()))throw bad("PRIORITY_INVALID","Mức độ hiện tại không hợp lệ.");changed(repo.reopen(id,p.id(),r.reason().trim(),r.recurringAt(),r.currentPriority(),r.preferredServiceTime(),r.version()));repo.history(id,"REOPENED","RESOLVED","REOPENED","Khách thuê yêu cầu xử lý lại: "+r.reason().trim(),p.id());repo.notifyManagers(longValue(m,"property_id"),"Yêu cầu sửa chữa được mở lại",str(m,"code"));return result(p,id);}
 @Override@Transactional(readOnly=true)public AiAvailability aiAvailability(AuthenticatedUser p){tenant(p);return new AiAvailability(aiAvailable,aiAvailable?"AI đã được cấu hình.":"Nhà cung cấp AI chưa được cấu hình; biểu mẫu vẫn hoạt động đầy đủ mà không dùng dữ liệu giả.");}
 private Detail detailOf(AuthenticatedUser p,Map<String,Object>m){long id=longValue(m,"id");String status=str(m,"status");Schedule schedule=repo.schedule(id);Location loc=new Location(longValue(m,"property_id"),str(m,"property_name"),str(m,"property_address"),str(m,"building_name"),str(m,"floor_name"),longValue(m,"room_id"),str(m,"room_code"),str(m,"area_code"),str(m,"area_code"),nullableLong(m,"contract_id") == null?0:longValue(m,"contract_id"),str(m,"contract_code"));Asset asset=m.get("asset_id")==null?null:new Asset(longValue(m,"asset_id"),str(m,"asset_name"),str(m,"asset_condition"));Technician tech=m.get("assigned_to")==null?null:new Technician(longValue(m,"assigned_to"),str(m,"technician_name"),"Nhân viên kỹ thuật");return new Detail(id,str(m,"code"),str(m,"title"),str(m,"description"),str(m,"issue_type"),str(m,"reported_priority"),str(m,"priority"),status,bool(m,"safety_risk"),bool(m,"continuous_issue"),nullableBool(m,"asset_usable"),dateTime(m,"detected_at"),dateTime(m,"created_at"),dateTime(m,"updated_at"),date(m,"preferred_date"),str(m,"preferred_time_slot"),str(m,"contact_phone"),str(m,"access_preference"),str(m,"access_note"),bool(m,"pets_present"),loc,asset,schedule,tech,repo.attachments(id),repo.timeline(id),repo.messages(id,p.id()),str(m,"diagnosis"),str(m,"resolution"),repo.feedback(id,p.id()),repo.cost(id),TenantMaintenanceRepository.permissions(status,schedule!=null),longValue(m,"version"));}
 private Map<String,Object>owned(AuthenticatedUser p,long id,boolean lock){tenant(p);return repo.request(p.id(),id,lock).orElseThrow(()->notFound("Không tìm thấy yêu cầu sửa chữa."));}private ActionResult result(AuthenticatedUser p,long id){Map<String,Object>x=owned(p,id,false);return new ActionResult(id,str(x,"status"),longValue(x,"version"));}
 private static String statuses(String x){if(x==null||x.isBlank()||"ALL".equals(x))return null;return switch(x){case"ACTIVE"->"SUBMITTED,RECEIVED,NEW,TRIAGED,ASSIGNED,SCHEDULED,IN_PROGRESS,WAITING_PARTS,REOPENED";case"NEEDS_RESPONSE"->"NEED_MORE_INFORMATION,WAITING_TENANT";case"INSPECTION"->"COMPLETED,INSPECTION_PENDING";case"DONE"->"RESOLVED";case"CANCELLED"->"CANCELLED,REJECTED";default->x;};}
 private static byte[]bytes(MultipartFile f){if(f==null||f.isEmpty())throw bad("ATTACHMENT_REQUIRED","Tệp rỗng.");try{return f.getBytes();}catch(IOException e){throw bad("ATTACHMENT_READ_FAILED","Không thể đọc tệp.");}}private static String detect(byte[]b){if(b.length>=4&&(b[0]&255)==255&&(b[1]&255)==216&&(b[2]&255)==255)return"image/jpeg";if(b.length>=8&&(b[0]&255)==137&&b[1]=='P'&&b[2]=='N'&&b[3]=='G')return"image/png";if(b.length>=12&&ascii(b,0,4).equals("RIFF")&&ascii(b,8,4).equals("WEBP"))return"image/webp";if(b.length>=12&&ascii(b,4,4).equals("ftyp"))return"video/mp4";return null;}private static String ascii(byte[]b,int o,int n){return new String(b,o,n,StandardCharsets.US_ASCII);}private static String validAttachmentType(String x){return Set.of("OVERVIEW","CLOSE_UP","ASSET","SAFETY","VIDEO","ADDITIONAL","AFTER").contains(x)?x:"ADDITIONAL";}private static String safe(String x){return x==null?"minh-chung":x.replaceAll("[\\\\/\\r\\n]","_");}
 private void tenant(AuthenticatedUser p){if(p==null||p.activeRole()!=RoleCode.TENANT)throw new AuthException(HttpStatus.FORBIDDEN,"TENANT_MAINTENANCE_DENIED","Bạn không có quyền truy cập yêu cầu sửa chữa của khách thuê.");}private static void changed(int n){if(n==0)throw conflict("MAINTENANCE_VERSION_CONFLICT","Yêu cầu đã được cập nhật hoặc trạng thái không còn cho phép. Vui lòng tải lại.");}
 private static String join(String a,String b){String x=clean(a),y=clean(b);return x==null?y:y==null?x:x+" · "+y;}private static String clean(String x){return x==null||x.isBlank()?null:x.trim();}private static String str(Map<String,Object>m,String k){Object x=m.get(k);return x==null?null:String.valueOf(x);}private static long longValue(Map<String,Object>m,String k){return ((Number)m.get(k)).longValue();}private static Long nullableLong(Map<String,Object>m,String k){return m.get(k)==null?null:longValue(m,k);}private static boolean bool(Map<String,Object>m,String k){Object x=m.get(k);return x!=null&&(Boolean)x;}private static Boolean nullableBool(Map<String,Object>m,String k){return m.get(k)==null?null:(Boolean)m.get(k);}private static LocalDateTime dateTime(Map<String,Object>m,String k){Object x=m.get(k);return x==null?null:x instanceof LocalDateTime d?d:((Timestamp)x).toLocalDateTime();}private static LocalDate date(Map<String,Object>m,String k){Object x=m.get(k);return x==null?null:x instanceof LocalDate d?d:((java.sql.Date)x).toLocalDate();}
 private static AuthException bad(String c,String m){return new AuthException(HttpStatus.BAD_REQUEST,c,m);}private static AuthException conflict(String c,String m){return new AuthException(HttpStatus.CONFLICT,c,m);}private static AuthException denied(String m){return new AuthException(HttpStatus.FORBIDDEN,"MAINTENANCE_LOCATION_DENIED",m);}private static AuthException notFound(String m){return new AuthException(HttpStatus.NOT_FOUND,"TENANT_MAINTENANCE_NOT_FOUND",m);}
}
