package com.thangit.boardinghouse.service.impl;

import static com.thangit.boardinghouse.dto.request.account.TenantAccountRequests.*;
import static com.thangit.boardinghouse.dto.response.account.TenantAccountResponses.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.thangit.boardinghouse.common.exception.AuthException;
import com.thangit.boardinghouse.domain.auth.RoleCode;
import com.thangit.boardinghouse.repository.*;
import com.thangit.boardinghouse.security.AuthenticatedUser;
import com.thangit.boardinghouse.service.TenantAccountService;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

@Service
public class TenantAccountServiceImpl implements TenantAccountService {
    private static final long MAX_FILE=5L*1024*1024;
    private static final Set<String> PROFILE_FIELDS=Set.of("fullName","dateOfBirth","permanentAddress","identityNumber","accountEmail","accountPhone");
    private final TenantAccountRepository repository;private final UserRepository users;private final RefreshTokenRepository tokens;private final PasswordEncoder encoder;private final ObjectMapper json=new ObjectMapper();
    public TenantAccountServiceImpl(TenantAccountRepository repository,UserRepository users,RefreshTokenRepository tokens,PasswordEncoder encoder){this.repository=repository;this.users=users;this.tokens=tokens;this.encoder=encoder;}

    @Override @Transactional(readOnly=true) public Overview overview(AuthenticatedUser p,String agent){tenant(p);var m=row(p);var profile=profileSummary(m);var residence=m.get("property_id")==null?null:new Residence(number(m,"property_id"),text(m,"property_name"),text(m,"property_address"),text(m,"building_name"),text(m,"floor_name"),nullableNumber(m,"room_id"),text(m,"room_code"),text(m,"residence_role"),text(m,"residence_status"),date(m,"move_in_date"),text(m,"temporary_status"));var contract=m.get("contract_id")==null?null:new Contract(number(m,"contract_id"),text(m,"contract_code"),date(m,"start_date"),date(m,"end_date"),text(m,"contract_status"));return new Overview(new Account(number(m,"id"),text(m,"account_email"),text(m,"account_email"),bool(m,"email_verified"),text(m,"account_phone"),bool(m,"phone_verified"),text(m,"account_status"),"TENANT",ldt(m,"account_created_at"),ldt(m,"last_login_at")),profile,residence,contract,new Security(false,false,repository.activeSessions(p.id()),ldt(m,"password_changed_at"),device(agent)),new PendingActions(repository.pendingDocuments(p.id()),repository.pendingUpdates(p.id()),repository.pendingResidence(p.id())),new Permissions(true,true,true,true,false));}
    @Override @Transactional(readOnly=true) public ProfileData profile(AuthenticatedUser p){tenant(p);return profileData(row(p));}
    @Override @Transactional public UpdateResult updateProfile(AuthenticatedUser p,UpdateProfile r){tenant(p);if(repository.phoneExists(r.phone(),p.id()))throw conflict("PHONE_EXISTS","Số điện thoại đã được sử dụng.");if(repository.emailExists(r.contactEmail(),p.id()))throw conflict("EMAIL_EXISTS","Email liên hệ đã được sử dụng.");if(r.emergencyContact()!=null&&!blank(r.emergencyContact().phone())&&normalize(r.phone()).equals(normalize(r.emergencyContact().phone())))throw bad("EMERGENCY_PHONE_DUPLICATE","Số liên hệ khẩn cấp phải khác số điện thoại của bạn.");if(repository.updateProfile(p.id(),r)==0)throw conflict("PROFILE_VERSION_CONFLICT","Thông tin đã được cập nhật ở thiết bị khác. Vui lòng tải lại.");repository.audit(p.id(),"PROFILE_UPDATED","Đã cập nhật thông tin liên hệ và hồ sơ cá nhân.");return new UpdateResult(profile(p),false);}
    @Override @Transactional public long createUpdateRequest(AuthenticatedUser p,ProfileUpdateRequest r){tenant(p);if(!PROFILE_FIELDS.containsAll(r.fieldChanges().keySet()))throw bad("PROFILE_FIELD_NOT_ALLOWED","Yêu cầu chứa trường không được phép cập nhật.");try{long id=repository.addUpdateRequest(p.id(),json.writeValueAsString(r.fieldChanges()),r.reason(),r.note());repository.audit(p.id(),"PROFILE_UPDATE_REQUESTED","Đã gửi yêu cầu cập nhật thông tin cần xác minh.");return id;}catch(Exception e){if(e instanceof AuthException a)throw a;throw new IllegalStateException(e);}}
    @Override @Transactional(readOnly=true) public List<UpdateRequestRow> updateRequests(AuthenticatedUser p){tenant(p);return repository.updateRequests(p.id());}

    @Override @Transactional public String saveAvatar(AuthenticatedUser p,MultipartFile file){tenant(p);var data=read(file,false);repository.saveAvatar(p.id(),safeName(file),file.getContentType(),data);repository.audit(p.id(),"AVATAR_UPDATED","Đã thay đổi ảnh đại diện.");return "/api/tenant/account/avatar/content";}
    @Override @Transactional public void deleteAvatar(AuthenticatedUser p){tenant(p);repository.deleteAvatar(p.id());repository.audit(p.id(),"AVATAR_DELETED","Đã xóa ảnh đại diện.");}
    @Override @Transactional(readOnly=true) public FileData avatar(AuthenticatedUser p){tenant(p);return repository.avatar(p.id()).orElseThrow(()->notFound("Không tìm thấy ảnh đại diện."));}
    @Override @Transactional(readOnly=true) public List<DocumentRow> documents(AuthenticatedUser p){tenant(p);return repository.documents(p.id());}
    @Override @Transactional public long saveDocument(AuthenticatedUser p,String type,String number,LocalDate issue,LocalDate expires,String side,String note,MultipartFile file){tenant(p);String t=upper(type);if(!Set.of("IDENTITY_CARD","PASSPORT","BIRTH_CERTIFICATE","TEMPORARY_RESIDENCE","OTHER").contains(t))throw bad("DOCUMENT_TYPE_INVALID","Loại giấy tờ không hợp lệ.");String s=upper(side);if(!Set.of("FRONT","BACK","SINGLE").contains(s))throw bad("DOCUMENT_SIDE_INVALID","Mặt giấy tờ không hợp lệ.");if(issue!=null&&expires!=null&&expires.isBefore(issue))throw bad("DOCUMENT_DATE_INVALID","Ngày hết hạn phải sau ngày cấp.");var data=read(file,true);String digits=number==null?null:number.replaceAll("\\D","");String last=digits==null||digits.isBlank()?null:digits.substring(Math.max(0,digits.length()-4));long id=repository.addDocument(p.id(),t,last,issue,expires,s,note,safeName(file),file.getContentType(),data);repository.audit(p.id(),"DOCUMENT_UPLOADED","Đã tải lên giấy tờ và gửi chờ xác minh.");return id;}
    @Override @Transactional(readOnly=true) public FileData document(AuthenticatedUser p,long id){tenant(p);return repository.document(p.id(),id).orElseThrow(()->notFound("Không tìm thấy giấy tờ."));}

    @Override @Transactional public void changePassword(AuthenticatedUser p,ChangePassword r){tenant(p);if(!r.newPassword().equals(r.confirmPassword()))throw bad("PASSWORD_CONFIRMATION_MISMATCH","Mật khẩu xác nhận không khớp.");if(r.currentPassword().equals(r.newPassword()))throw bad("PASSWORD_UNCHANGED","Mật khẩu mới phải khác mật khẩu hiện tại.");if(!strong(r.newPassword()))throw bad("PASSWORD_WEAK","Mật khẩu mới cần ít nhất 8 ký tự, có chữ hoa, chữ thường và chữ số.");var u=users.findById(p.id()).orElseThrow(()->notFound("Không tìm thấy tài khoản."));if(!encoder.matches(r.currentPassword(),u.getPasswordHash()))throw bad("CURRENT_PASSWORD_INVALID","Mật khẩu hiện tại không chính xác.");u.changePassword(encoder.encode(r.newPassword()));users.save(u);if(r.logoutOtherSessions())tokens.revokeAllForUser(p.id(),Instant.now());repository.audit(p.id(),"PASSWORD_CHANGED","Đã thay đổi mật khẩu tài khoản.");}
    @Override @Transactional(readOnly=true) public List<SessionRow> sessions(AuthenticatedUser p,String raw){tenant(p);String current=hash(raw);return repository.sessions(p.id()).stream().map(s->{var ua=parseAgent(s.userAgent());return new SessionRow(s.id(),ua[0],ua[1],ua[2],maskIp(s.ipAddress()),current!=null&&current.equals(s.tokenHash()),s.active(),s.createdAt(),s.lastActiveAt());}).toList();}
    @Override @Transactional public void revokeSession(AuthenticatedUser p,long id){tenant(p);if(repository.revokeSession(p.id(),id)==0)throw notFound("Không tìm thấy phiên đăng nhập đang hoạt động.");repository.audit(p.id(),"SESSION_REVOKED","Đã thu hồi một phiên đăng nhập.");}
    @Override @Transactional public int revokeAll(AuthenticatedUser p,RevokeAllSessions r,String raw){tenant(p);int n=repository.revokeAll(p.id(),r.keepCurrentSession()?hash(raw):null);repository.audit(p.id(),"SESSIONS_REVOKED","Đã thu hồi các phiên đăng nhập khác.");return n;}
    @Override @Transactional(readOnly=true) public PreferenceData preferences(AuthenticatedUser p){tenant(p);return repository.preferences(p.id()).orElse(new PreferenceData("vi","SYSTEM","Asia/Ho_Chi_Minh","dd/MM/yyyy","HH:mm",false,0));}
    @Override @Transactional public PreferenceData preferences(AuthenticatedUser p,Preferences r){tenant(p);try{ZoneId.of(r.timezone());}catch(Exception e){throw bad("TIMEZONE_INVALID","Múi giờ không hợp lệ.");}if(repository.savePreferences(p.id(),r.language(),r.theme(),r.timezone(),r.dateFormat(),r.timeFormat(),r.reducedMotion(),r.version())==0)throw conflict("PREFERENCE_VERSION_CONFLICT","Cài đặt đã được cập nhật ở thiết bị khác. Vui lòng tải lại.");repository.audit(p.id(),"PREFERENCES_UPDATED","Đã cập nhật tùy chọn tài khoản.");return preferences(p);}
    @Override @Transactional(readOnly=true) public Page<ActivityRow> activities(AuthenticatedUser p,int page,int size){tenant(p);if(page<0||size<1||size>50)throw bad("PAGINATION_INVALID","Thông tin phân trang không hợp lệ.");return repository.activities(p.id(),page,size);}
    @Override @Transactional(readOnly=true) public SupportInfo supportInfo(AuthenticatedUser p){tenant(p);return repository.supportInfo(p.id()).orElse(new SupportInfo(null,null,"Theo thông tin quản lý tại khu trọ",true));}
    @Override @Transactional public SupportResult support(AuthenticatedUser p,String subject,String content,String priority,String contact,MultipartFile file){tenant(p);if(subject==null||subject.isBlank()||subject.length()>200||content==null||content.isBlank()||content.length()>3000)throw bad("SUPPORT_CONTENT_INVALID","Vui lòng nhập đầy đủ chủ đề và nội dung hỗ trợ.");String pri=upper(priority);if(!Set.of("LOW","NORMAL","HIGH").contains(pri))pri="NORMAL";String channel=upper(contact);if(!Set.of("EMAIL","PHONE").contains(channel))channel="EMAIL";byte[] bytes=null;String name=null,type=null;if(file!=null&&!file.isEmpty()){bytes=read(file,true);name=safeName(file);type=file.getContentType();}long id=repository.support(p.id(),subject.trim(),content.trim(),pri,channel,name,type,bytes);repository.audit(p.id(),"SUPPORT_REQUESTED","Đã gửi yêu cầu hỗ trợ tài khoản.");return new SupportResult(id,"HT%06d".formatted(id),"OPEN",LocalDateTime.now());}

    private Map<String,Object> row(AuthenticatedUser p){tenant(p);return repository.account(p.id()).orElseThrow(()->notFound("Không tìm thấy hồ sơ khách thuê."));}
    private ProfileData profileData(Map<String,Object> m){return new ProfileData(profileSummary(m),text(m,"phone"),text(m,"email"),bool(m,"email_verified"),bool(m,"phone_verified"),text(m,"permanent_address"),new com.thangit.boardinghouse.dto.response.account.TenantAccountResponses.EmergencyContact(text(m,"emergency_contact_name"),text(m,"emergency_contact_relationship"),text(m,"emergency_contact_phone"),text(m,"emergency_contact_address")),text(m,"account_status"),text(m,"residence_role"),text(m,"room_code"),text(m,"contract_code"),text(m,"temporary_status"),date(m,"move_in_date"));}
    private Profile profileSummary(Map<String,Object> m){var missing=new ArrayList<String>();if(blank(text(m,"full_name")))missing.add("Họ và tên");if(m.get("date_of_birth")==null)missing.add("Ngày sinh");if(blank(text(m,"phone")))missing.add("Số điện thoại");if(blank(text(m,"permanent_address")))missing.add("Địa chỉ thường trú");if(blank(text(m,"occupation")))missing.add("Nghề nghiệp");int percent=Math.max(0,100-missing.size()*20);return new Profile(number(m,"profile_id"),text(m,"tenant_code"),text(m,"full_name"),text(m,"avatar_url"),date(m,"date_of_birth"),text(m,"gender"),text(m,"nationality"),text(m,"occupation"),text(m,"workplace"),text(m,"profile_status"),percent,missing,((Number)m.get("version")).longValue());}
    private byte[] read(MultipartFile f,boolean pdf){if(f==null||f.isEmpty()||f.getSize()>MAX_FILE)throw bad("FILE_SIZE_INVALID","Tệp phải có dung lượng từ 1 byte đến 5 MB.");try{byte[] b=f.getBytes();String actual=sniff(b);if(actual==null||(!pdf&&"application/pdf".equals(actual))||!actual.equals(f.getContentType()))throw bad("FILE_TYPE_INVALID",pdf?"Chỉ chấp nhận JPG, PNG, WEBP hoặc PDF hợp lệ.":"Chỉ chấp nhận JPG, PNG hoặc WEBP hợp lệ.");return b;}catch(IOException e){throw bad("FILE_READ_ERROR","Không thể đọc tệp tải lên.");}}
    private static String sniff(byte[] b){if(b.length>4&&b[0]==(byte)0xFF&&b[1]==(byte)0xD8&&b[2]==(byte)0xFF)return"image/jpeg";if(b.length>8&&b[0]==(byte)0x89&&b[1]==0x50&&b[2]==0x4E&&b[3]==0x47)return"image/png";if(b.length>12&&new String(b,0,4,StandardCharsets.US_ASCII).equals("RIFF")&&new String(b,8,4,StandardCharsets.US_ASCII).equals("WEBP"))return"image/webp";if(b.length>5&&new String(b,0,5,StandardCharsets.US_ASCII).equals("%PDF-"))return"application/pdf";return null;}
    private static String safeName(MultipartFile f){String n=f.getOriginalFilename();return n==null?"file":n.replaceAll("[\\\\/\\r\\n]","_");}
    private static boolean strong(String s){return s.length()>=8&&s.chars().anyMatch(Character::isUpperCase)&&s.chars().anyMatch(Character::isLowerCase)&&s.chars().anyMatch(Character::isDigit);}
    private static String[] parseAgent(String ua){String value=ua==null?"":ua;String browser=value.contains("Edg/")?"Edge":value.contains("Chrome/")?"Chrome":value.contains("Firefox/")?"Firefox":value.contains("Safari/")?"Safari":"Trình duyệt không xác định";String os=value.contains("Windows")?"Windows":value.contains("Android")?"Android":value.contains("iPhone")||value.contains("iPad")?"iOS":value.contains("Mac OS")?"macOS":value.contains("Linux")?"Linux":"Hệ điều hành không xác định";return new String[]{browser+" trên "+os,browser,os};}
    private static String device(String ua){return parseAgent(ua)[0];}
    private static String maskIp(String ip){if(ip==null||ip.isBlank())return"Không xác định";if(ip.contains(":"))return ip.substring(0,Math.min(4,ip.length()))+":****";var p=ip.split("\\.");return p.length==4?p[0]+".***.***."+p[3]:"***";}
    private static String hash(String raw){if(raw==null||raw.isBlank())return null;try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private static String normalize(String s){return s==null?"":s.replaceAll("[ .()-]","");}private static String upper(String s){return s==null?"":s.trim().toUpperCase(Locale.ROOT);}private static boolean blank(String s){return s==null||s.isBlank();}
    private static String text(Map<String,Object> m,String k){Object v=m.get(k);return v==null?null:v.toString();}private static boolean bool(Map<String,Object> m,String k){Object v=m.get(k);return v instanceof Boolean b?b:v instanceof Number n&&n.intValue()!=0;}private static long number(Map<String,Object> m,String k){return((Number)m.get(k)).longValue();}private static Long nullableNumber(Map<String,Object> m,String k){return m.get(k)==null?null:number(m,k);}private static LocalDate date(Map<String,Object> m,String k){Object v=m.get(k);return v==null?null:v instanceof LocalDate d?d:((java.sql.Date)v).toLocalDate();}private static LocalDateTime ldt(Map<String,Object> m,String k){Object v=m.get(k);return v==null?null:v instanceof LocalDateTime d?d:v instanceof Timestamp t?t.toLocalDateTime():LocalDateTime.ofInstant((Instant)v,ZoneOffset.UTC);}
    private void tenant(AuthenticatedUser p){if(p==null||p.activeRole()!=RoleCode.TENANT)throw new AuthException(HttpStatus.FORBIDDEN,"ACCOUNT_ROLE_FORBIDDEN","Chỉ khách thuê được truy cập tài khoản này.");}
    private AuthException bad(String c,String m){return new AuthException(HttpStatus.BAD_REQUEST,c,m);}private AuthException conflict(String c,String m){return new AuthException(HttpStatus.CONFLICT,c,m);}private AuthException notFound(String m){return new AuthException(HttpStatus.NOT_FOUND,"TENANT_ACCOUNT_NOT_FOUND",m);}
}
