CREATE TABLE tenant_payment_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    invoice_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'AWAITING_TRANSFER',
    transfer_content VARCHAR(255) NULL,
    expires_at DATETIME(6) NOT NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_tenant_payment_session_key UNIQUE (tenant_id,idempotency_key),
    CONSTRAINT fk_tenant_payment_session_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    CONSTRAINT fk_tenant_payment_session_tenant FOREIGN KEY (tenant_id) REFERENCES users(id),
    CONSTRAINT chk_tenant_payment_session_amount CHECK (amount > 0),
    INDEX idx_tenant_payment_session_invoice (invoice_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tenant_payment_proofs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    session_id BIGINT UNSIGNED NULL,
    invoice_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    transferred_at DATETIME(6) NOT NULL,
    bank_name VARCHAR(150) NULL,
    transaction_reference VARCHAR(100) NULL,
    original_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    file_content LONGBLOB NOT NULL,
    note VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at DATETIME(6) NULL,
    rejection_reason VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_tenant_payment_proof_session FOREIGN KEY (session_id) REFERENCES tenant_payment_sessions(id),
    CONSTRAINT fk_tenant_payment_proof_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    CONSTRAINT fk_tenant_payment_proof_tenant FOREIGN KEY (tenant_id) REFERENCES users(id),
    CONSTRAINT fk_tenant_payment_proof_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id),
    CONSTRAINT chk_tenant_payment_proof_amount CHECK (amount > 0),
    INDEX idx_tenant_payment_proof_invoice (invoice_id,created_at),
    INDEX idx_tenant_payment_proof_status (status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tenant_invoice_review_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    request_code VARCHAR(50) NOT NULL,
    invoice_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    invoice_item_id BIGINT UNSIGNED NULL,
    issue_type VARCHAR(40) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    expected_value VARCHAR(255) NULL,
    contact_phone VARCHAR(30) NULL,
    preferred_contact_time VARCHAR(100) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    manager_response VARCHAR(1000) NULL,
    resolved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_tenant_invoice_review_code UNIQUE (request_code),
    CONSTRAINT fk_tenant_invoice_review_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    CONSTRAINT fk_tenant_invoice_review_tenant FOREIGN KEY (tenant_id) REFERENCES users(id),
    CONSTRAINT fk_tenant_invoice_review_item FOREIGN KEY (invoice_item_id) REFERENCES invoice_items(id),
    INDEX idx_tenant_invoice_review_invoice (invoice_id,created_at),
    INDEX idx_tenant_invoice_review_status (status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
