CREATE TABLE rental_bookings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    code VARCHAR(40) NOT NULL,
    property_id BIGINT UNSIGNED NOT NULL,
    room_id BIGINT UNSIGNED NOT NULL,
    tenant_profile_id BIGINT UNSIGNED NOT NULL,
    contract_id BIGINT UNSIGNED NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RESERVED',
    reservation_start DATE NOT NULL,
    reservation_end DATE NOT NULL,
    deposit_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    deposit_status VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    source VARCHAR(50) NULL,
    note VARCHAR(1000) NULL,
    created_by BIGINT UNSIGNED NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_rental_bookings_code UNIQUE (code),
    CONSTRAINT fk_booking_property FOREIGN KEY (property_id) REFERENCES properties(id),
    CONSTRAINT fk_booking_room FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT fk_booking_tenant_profile FOREIGN KEY (tenant_profile_id) REFERENCES tenant_profiles(id),
    CONSTRAINT fk_booking_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_booking_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_booking_dates CHECK (reservation_end >= reservation_start),
    CONSTRAINT chk_booking_deposit CHECK (deposit_amount >= 0),
    INDEX idx_booking_property_status (property_id,status,reservation_start),
    INDEX idx_booking_room_status (room_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rental_booking_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id BIGINT UNSIGNED NOT NULL,
    previous_status VARCHAR(30) NULL,
    new_status VARCHAR(30) NOT NULL,
    description VARCHAR(500) NULL,
    actor_id BIGINT UNSIGNED NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_booking_history_booking FOREIGN KEY (booking_id) REFERENCES rental_bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_history_actor FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_booking_history_time (booking_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rental_checkins (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    contract_id BIGINT UNSIGNED NOT NULL,
    booking_id BIGINT UNSIGNED NULL,
    scheduled_date DATE NOT NULL,
    actual_checkin_at DATETIME(6) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    identity_verified BOOLEAN NOT NULL DEFAULT FALSE,
    contract_verified BOOLEAN NOT NULL DEFAULT FALSE,
    deposit_verified BOOLEAN NOT NULL DEFAULT FALSE,
    electricity_reading DECIMAL(12,2) NULL,
    water_reading DECIMAL(12,2) NULL,
    keys_cards_count INT NOT NULL DEFAULT 0,
    note VARCHAR(1000) NULL,
    created_by BIGINT UNSIGNED NULL,
    completed_by BIGINT UNSIGNED NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_rental_checkin_contract UNIQUE (contract_id),
    CONSTRAINT fk_checkin_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_checkin_booking FOREIGN KEY (booking_id) REFERENCES rental_bookings(id),
    CONSTRAINT fk_checkin_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_checkin_completer FOREIGN KEY (completed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_checkin_meter CHECK ((electricity_reading IS NULL OR electricity_reading >= 0) AND (water_reading IS NULL OR water_reading >= 0)),
    INDEX idx_checkin_status_date (status,scheduled_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rental_checkin_assets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    checkin_id BIGINT UNSIGNED NOT NULL,
    room_asset_id BIGINT UNSIGNED NULL,
    asset_name VARCHAR(150) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    condition_status VARCHAR(30) NOT NULL,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_checkin_asset_checkin FOREIGN KEY (checkin_id) REFERENCES rental_checkins(id) ON DELETE CASCADE,
    CONSTRAINT fk_checkin_asset_room_asset FOREIGN KEY (room_asset_id) REFERENCES room_assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rental_checkouts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    contract_id BIGINT UNSIGNED NOT NULL,
    requested_date DATE NOT NULL,
    confirmed_date DATE NULL,
    actual_checkout_at DATETIME(6) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',
    final_electricity_reading DECIMAL(12,2) NULL,
    final_water_reading DECIMAL(12,2) NULL,
    deposit_held DECIMAL(15,2) NOT NULL DEFAULT 0,
    outstanding_debt DECIMAL(15,2) NOT NULL DEFAULT 0,
    additional_charges DECIMAL(15,2) NOT NULL DEFAULT 0,
    refund_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    balance_due DECIMAL(15,2) NOT NULL DEFAULT 0,
    reason VARCHAR(500) NULL,
    note VARCHAR(1000) NULL,
    created_by BIGINT UNSIGNED NULL,
    completed_by BIGINT UNSIGNED NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_rental_checkout_contract UNIQUE (contract_id),
    CONSTRAINT fk_checkout_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_checkout_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_checkout_completer FOREIGN KEY (completed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_checkout_amounts CHECK (deposit_held >= 0 AND outstanding_debt >= 0 AND additional_charges >= 0 AND refund_amount >= 0 AND balance_due >= 0),
    INDEX idx_checkout_status_date (status,requested_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rental_checkout_charges (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    checkout_id BIGINT UNSIGNED NOT NULL,
    charge_type VARCHAR(40) NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_checkout_charge_checkout FOREIGN KEY (checkout_id) REFERENCES rental_checkouts(id) ON DELETE CASCADE,
    CONSTRAINT chk_checkout_charge_amount CHECK (amount >= 0),
    INDEX idx_checkout_charges (checkout_id,charge_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

