CREATE TABLE system_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    owner_id BIGINT UNSIGNED NOT NULL,
    setting_group VARCHAR(50) NOT NULL,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT NULL,
    value_type VARCHAR(20) NOT NULL DEFAULT 'STRING',
    is_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    updated_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_system_setting_owner_group_key UNIQUE (owner_id, setting_group, setting_key),
    CONSTRAINT fk_system_setting_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_system_setting_updater FOREIGN KEY (updated_by) REFERENCES users (id),
    INDEX idx_system_setting_group (owner_id, setting_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE property_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    property_id BIGINT UNSIGNED NOT NULL,
    manager_name VARCHAR(150) NULL,
    manager_phone VARCHAR(30) NULL,
    manager_email VARCHAR(190) NULL,
    working_hours VARCHAR(100) NULL,
    billing_day TINYINT UNSIGNED NOT NULL DEFAULT 1,
    payment_due_day TINYINT UNSIGNED NOT NULL DEFAULT 5,
    meter_reading_day TINYINT UNSIGNED NOT NULL DEFAULT 28,
    default_maximum_occupants TINYINT UNSIGNED NOT NULL DEFAULT 3,
    quiet_hours_start TIME NULL,
    quiet_hours_end TIME NULL,
    allow_pets BOOLEAN NOT NULL DEFAULT FALSE,
    allow_visitors BOOLEAN NOT NULL DEFAULT TRUE,
    visitor_rules TEXT NULL,
    vehicle_rules TEXT NULL,
    house_rules TEXT NULL,
    emergency_contact VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    updated_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_property_settings_property UNIQUE (property_id),
    CONSTRAINT fk_property_settings_property FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE,
    CONSTRAINT fk_property_settings_updater FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE billing_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    owner_id BIGINT UNSIGNED NOT NULL,
    auto_generate_invoices BOOLEAN NOT NULL DEFAULT FALSE,
    invoice_generation_day TINYINT UNSIGNED NOT NULL DEFAULT 1,
    default_due_day TINYINT UNSIGNED NOT NULL DEFAULT 5,
    allow_partial_payment BOOLEAN NOT NULL DEFAULT TRUE,
    carry_forward_debt BOOLEAN NOT NULL DEFAULT TRUE,
    late_fee_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    late_fee_type VARCHAR(20) NOT NULL DEFAULT 'FIXED',
    late_fee_value DECIMAL(15,2) NOT NULL DEFAULT 0,
    reminder_days_before_due VARCHAR(100) NOT NULL DEFAULT '3,1',
    reminder_days_after_due VARCHAR(100) NOT NULL DEFAULT '1,3,7',
    require_cancellation_reason BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    updated_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_billing_settings_owner UNIQUE (owner_id),
    CONSTRAINT fk_billing_settings_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_billing_settings_updater FOREIGN KEY (updated_by) REFERENCES users (id),
    CONSTRAINT chk_billing_late_fee_non_negative CHECK (late_fee_value >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ai_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    owner_id BIGINT UNSIGNED NOT NULL,
    provider VARCHAR(30) NULL,
    model VARCHAR(100) NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    tenant_chatbot BOOLEAN NOT NULL DEFAULT FALSE,
    invoice_explanation BOOLEAN NOT NULL DEFAULT FALSE,
    contract_explanation BOOLEAN NOT NULL DEFAULT FALSE,
    maintenance_classification BOOLEAN NOT NULL DEFAULT FALSE,
    utility_anomaly_detection BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_request_limit INT UNSIGNED NOT NULL DEFAULT 10000,
    response_language VARCHAR(10) NOT NULL DEFAULT 'vi',
    request_timeout_seconds INT UNSIGNED NOT NULL DEFAULT 30,
    store_conversation_history BOOLEAN NOT NULL DEFAULT FALSE,
    history_retention_days INT UNSIGNED NOT NULL DEFAULT 30,
    require_action_confirmation BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    updated_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_ai_settings_owner UNIQUE (owner_id),
    CONSTRAINT fk_ai_settings_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_ai_settings_updater FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE setting_audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    setting_group VARCHAR(50) NOT NULL,
    scope_type VARCHAR(20) NOT NULL,
    scope_id BIGINT UNSIGNED NULL,
    action VARCHAR(30) NOT NULL,
    old_value TEXT NULL,
    new_value TEXT NULL,
    result VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_setting_audit_user FOREIGN KEY (user_id) REFERENCES users (id),
    INDEX idx_setting_audit_time (created_at),
    INDEX idx_setting_audit_scope (setting_group, scope_type, scope_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
