package com.thangit.boardinghouse.controller;
import static com.thangit.boardinghouse.dto.response.maintenance.TenantMaintenanceResponses.*;import com.thangit.boardinghouse.common.base.ApiResponse;import com.thangit.boardinghouse.dto.request.maintenance.TenantMaintenanceRequests.*;import com.thangit.boardinghouse.security.AuthenticatedUser;import com.thangit.boardinghouse.service.TenantMaintenanceService;import jakarta.validation.Valid;
import java.nio.charset.StandardCharsets;import java.time.LocalDate;import java.util.List;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.*;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
@RestController@RequestMapping("/api/tenant/maintenance")public class TenantMaintenanceController{
 private final TenantMaintenanceService service;public TenantMaintenanceController(TenantMaintenanceService service){this.service=service;}
 @GetMapping("/summary")public ApiResponse<Summary>summary(@AuthenticationPrincipal AuthenticatedUser p){return ApiResponse.success("Lấy thống kê yêu cầu sửa chữa thành công.",service.summary(p));}
 @GetMapping("/available-locations")public ApiResponse<List<AvailableLocation>>locations(@AuthenticationPrincipal AuthenticatedUser p){return ApiResponse.success("Lấy vị trí đang thuê thành công.",service.locations(p));}
 @GetMapping("/ai-availability")public ApiResponse<AiAvailability>ai(@AuthenticationPrincipal AuthenticatedUser p){return ApiResponse.success("Kiểm tra cấu hình AI thành công.",service.aiAvailability(p));}
 @GetMapping public ApiResponse<Page<RequestRow>>list(@AuthenticationPrincipal AuthenticatedUser p,@RequestParam(required=false)String status,@RequestParam(required=false)String keyword,@RequestParam(required=false)String category,@RequestParam(required=false)String priority,@RequestParam(required=false)Long roomId,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate startDate,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate endDate,@RequestParam(defaultValue="newest")String sort,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size){return ApiResponse.success("Lấy danh sách yêu cầu sửa chữa thành công.",service.list(p,status,keyword,category,priority,roomId,startDate,endDate,sort,page,size));}
 @PostMapping public ResponseEntity<ApiResponse<Created>>create(@AuthenticationPrincipal AuthenticatedUser p,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody CreateRequest r){return ResponseEntity.status(201).body(ApiResponse.success("Yêu cầu sửa chữa đã được gửi thành công.",service.create(p,key,r)));}
 @GetMapping("/{id}")public ApiResponse<Detail>detail(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long id){return ApiResponse.success("Lấy chi tiết yêu cầu sửa chữa thành công.",service.detail(p,id));}
 @PostMapping(value="/{id}/attachments",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)public ResponseEntity<ApiResponse<Uploaded>>upload(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long id,@RequestPart("files")List<MultipartFile>files,@RequestParam(defaultValue="ADDITIONAL")String attachmentType,@RequestParam(required=false)String caption){return ResponseEntity.status(201).body(ApiResponse.success("Tệp đã được tải lên.",service.upload(p,id,files,attachmentType,caption)));}
 @GetMapping("/attachments/{attachmentId}")public ResponseEntity<byte[]>file(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long attachmentId){FileData f=service.file(p,attachmentId);return ResponseEntity.ok().contentType(MediaType.parseMediaType(f.mimeType())).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.inline().filename(f.fileName(),StandardCharsets.UTF_8).build().toString()).contentLength(f.content().length).body(f.content());}
 @GetMapping("/{id}/messages")public ApiResponse<List<MessageItem>>messages(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long id){return ApiResponse.success("Lấy trao đổi thành công.",service.messages(p,id));}
 @PostMapping("/{id}/messages")public ResponseEntity<ApiResponse<MessageItem>>message(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long id,@Valid@RequestBody Message r){return ResponseEntity.status(201).body(ApiResponse.success("Tin nhắn đã được gửi.",service.message(p,id,r)));}
 @PostMapping("/{id}/additional-information")public ApiResponse<ActionResult>additional(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long id,@Valid@RequestBody AdditionalInformation r){return ApiResponse.success("Thông tin bổ sung đã được gửi.",service.additional(p,id,r));}
 @PostMapping("/{id}/schedule-responses")public ApiResponse<ActionResult>schedule(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long id,@Valid@RequestBody ScheduleResponse r){return ApiResponse.success("Phản hồi lịch xử lý đã được ghi nhận.",service.schedule(p,id,r));}
 @PostMapping("/{id}/cancel")public ApiResponse<ActionResult>cancel(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long id,@Valid@RequestBody Cancel r){return ApiResponse.success("Yêu cầu đã được hủy.",service.cancel(p,id,r));}
 @PostMapping("/{id}/feedback")public ApiResponse<ActionResult>feedback(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long id,@Valid@RequestBody Feedback r){return ApiResponse.success("Cảm ơn bạn đã đánh giá.",service.feedback(p,id,r));}
 @PostMapping("/{id}/reopen")public ApiResponse<ActionResult>reopen(@AuthenticationPrincipal AuthenticatedUser p,@PathVariable long id,@Valid@RequestBody Reopen r){return ApiResponse.success("Yêu cầu đã được mở lại.",service.reopen(p,id,r));}
}
