export type Party = { id: number; name: string; secondary?: string };
export type Option = { id: number; label: string; parentId?: number };
export type InvoiceSummary = {
  totalInvoiceAmount: number;
  totalPaidAmount: number;
  totalOutstandingAmount: number;
  collectionRate: number;
  draftInvoiceCount: number;
  unpaidInvoiceCount: number;
  partiallyPaidInvoiceCount: number;
  paidInvoiceCount: number;
  overdueInvoiceCount: number;
};
export type InvoiceRow = {
  id: number;
  invoiceCode: string;
  billingPeriod: string;
  property: Party;
  room: Party;
  tenant: Party;
  contract: Party;
  issueDate?: string;
  dueDate: string;
  totalAmount: number;
  paidAmount: number;
  remainingAmount: number;
  overdueDays: number;
  status: string;
  createdBy?: Party;
  automated: boolean;
  hasAdjustment: boolean;
  version: number;
  createdAt: string;
};
export type Page<T> = {
  content: T[];
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
};
export type InvoiceFilters = {
  propertyId?: number;
  buildingId?: number;
  floorId?: number;
  roomId?: number;
  keyword?: string;
  billingPeriod?: string;
  status?: string;
  overdue?: boolean;
  minimumAmount?: number;
  maximumAmount?: number;
  sort?: string;
  page?: number;
  size?: number;
};
export type InvoiceOptions = {
  properties: Option[];
  buildings: Option[];
  floors: Option[];
  rooms: Option[];
  contracts: Option[];
};
export type InvoiceItem = {
  id: number;
  itemType: string;
  name: string;
  description?: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  amount: number;
  sourceType?: string;
  sourceId?: number;
};
export type InvoicePayment = {
  id: number;
  receiptCode: string;
  amount: number;
  paymentMethod: string;
  referenceCode?: string;
  note?: string;
  status: string;
  receiverName?: string;
  paidAt: string;
};
export type InvoiceAdjustment = {
  id: number;
  code: string;
  type: string;
  amount: number;
  reason: string;
  status: string;
  requesterName?: string;
  createdAt: string;
};
export type InvoiceNotification = {
  id: number;
  channel: string;
  recipient: string;
  status: string;
  sentAt?: string;
  createdAt: string;
};
export type InvoiceHistory = {
  id: number;
  action: string;
  previousStatus?: string;
  newStatus?: string;
  reason?: string;
  actorName?: string;
  createdAt: string;
};
export type InvoicePermissions = {
  canEdit: boolean;
  canIssue: boolean;
  canRecordPayment: boolean;
  canSendReminder: boolean;
  canAdjust: boolean;
  canCancel: boolean;
  canDownload: boolean;
  canPrint: boolean;
};
export type InvoiceDetail = {
  id: number;
  invoiceCode: string;
  billingPeriod: string;
  periodStartDate: string;
  periodEndDate: string;
  issueDate?: string;
  dueDate: string;
  status: string;
  property: Party;
  room: Party;
  tenant: Party;
  contract: Party;
  items: InvoiceItem[];
  subtotalAmount: number;
  discountAmount: number;
  previousDebtAmount: number;
  lateFeeAmount: number;
  totalAmount: number;
  paidAmount: number;
  remainingAmount: number;
  note?: string;
  payments: InvoicePayment[];
  adjustments: InvoiceAdjustment[];
  notifications: InvoiceNotification[];
  history: InvoiceHistory[];
  permissions: InvoicePermissions;
  version: number;
};
export type AdditionalItem = {
  name: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  reason: string;
};
export type InvoicePayload = {
  roomId: number;
  contractId: number;
  billingPeriod: string;
  periodStartDate: string;
  periodEndDate: string;
  issueDate: string;
  dueDate: string;
  additionalItems: AdditionalItem[];
  discountAmount: number;
  includePreviousDebt: boolean;
  note?: string;
  action: "SAVE_DRAFT" | "ISSUE";
  version?: number;
};
export type BulkInvoicePayload = {
  propertyId: number;
  billingPeriod: string;
  issueDate: string;
  dueDate: string;
  roomIds?: number[];
  action?: "SAVE_DRAFT" | "ISSUE";
};
export type BulkPreview = {
  roomId: number;
  roomCode: string;
  tenantName: string;
  estimatedAmount: number;
  status: string;
  warning?: string;
};
