export type Page<T> = {
  content: T[];
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
};
export type MaintenancePermissions = {
  canView: boolean;
  canCancel: boolean;
  canAddInformation: boolean;
  canConfirmSchedule: boolean;
  canRequestReschedule: boolean;
  canSendMessage: boolean;
  canProvideFeedback: boolean;
  canReopen: boolean;
  canUpload: boolean;
};
export type MaintenanceSummary = {
  openRequestCount: number;
  inProgressRequestCount: number;
  needsTenantResponseCount: number;
  inspectionPendingCount: number;
  resolvedThisMonthCount: number;
};
export type MaintenanceRow = {
  id: number;
  requestCode: string;
  title: string;
  category: string;
  priority: string;
  propertyName: string;
  roomCode: string;
  areaCode: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  scheduledAt?: string;
  technicianName?: string;
  thumbnailAttachmentId?: number;
  permissions: MaintenancePermissions;
  version: number;
};
export type Location = {
  propertyId: number;
  propertyName: string;
  propertyAddress: string;
  buildingName?: string;
  floorName?: string;
  roomId: number;
  roomCode: string;
  areaCode: string;
  areaName: string;
  contractId: number;
  contractCode: string;
};
export type Asset = { id: number; name: string; conditionStatus: string };
export type AvailableLocation = {
  location: Location;
  assets: Asset[];
  managerPhone?: string;
};
export type Attachment = {
  id: number;
  attachmentType: string;
  fileName: string;
  mimeType: string;
  fileSize: number;
  caption?: string;
  uploadedBy: number;
  createdAt: string;
  downloadUrl: string;
};
export type MaintenanceMessage = {
  id: number;
  senderId: number;
  senderName: string;
  mine: boolean;
  messageType: string;
  content: string;
  createdAt: string;
  readAt?: string;
};
export type TimelineItem = {
  id: number;
  action: string;
  previousStatus?: string;
  newStatus?: string;
  description: string;
  actorName: string;
  createdAt: string;
};
export type MaintenanceSchedule = {
  id: number;
  scheduledStart: string;
  scheduledEnd: string;
  durationMinutes: number;
  tenantPresenceRequired: boolean;
  status: string;
  tenantResponse?: string;
  responseAt?: string;
};
export type FeedbackInfo = {
  result: string;
  rating: number;
  staffAttitudeRating?: number;
  resolutionTimeRating?: number;
  comment?: string;
  assetWorking: boolean;
  createdAt: string;
};
export type MaintenanceDetail = {
  id: number;
  requestCode: string;
  title: string;
  description: string;
  category: string;
  tenantReportedPriority: string;
  confirmedPriority: string;
  status: string;
  safetyRisk: boolean;
  continuousIssue: boolean;
  assetUsable?: boolean;
  detectedAt: string;
  createdAt: string;
  updatedAt: string;
  preferredDate: string;
  preferredTimeSlot: string;
  contactPhone: string;
  accessPreference: string;
  accessNote?: string;
  petsPresent: boolean;
  location: Location;
  asset?: Asset;
  schedule?: MaintenanceSchedule;
  technician?: { id: number; fullName: string; position: string };
  attachments: Attachment[];
  publicTimeline: TimelineItem[];
  messages: MaintenanceMessage[];
  diagnosis?: string;
  resolution?: string;
  feedback?: FeedbackInfo;
  tenantCost?: {
    amount: number;
    responsibility: string;
    approvalStatus: string;
  };
  permissions: MaintenancePermissions;
  version: number;
};
export type CreateMaintenance = {
  roomId: number;
  areaCode: string;
  assetId?: number;
  title: string;
  description: string;
  category: string;
  reportedPriority: string;
  detectedAt: string;
  safetyRisk: boolean;
  continuousIssue: boolean;
  assetUsable?: boolean;
  preferredSchedule: {
    preferredDate: string;
    timeSlot: string;
    tenantPresenceRequired: boolean;
    accessPreference: string;
    accessNote?: string;
    petsPresent: boolean;
  };
  contactPhone: string;
  note?: string;
};
export type ActionResult = { id: number; status: string; version: number };
