package com.thangit.boardinghouse.repository;

import com.thangit.boardinghouse.dto.request.accountant.AccountantRequests.*;
import java.math.BigDecimal;
import java.sql.*;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.jdbc.support.*;
import org.springframework.stereotype.Repository;

@Repository
public class AccountantPortalRepository {
    private final JdbcClient jdbc;
    public AccountantPortalRepository(JdbcClient jdbc){this.jdbc=jdbc;}

    public boolean profileExists(long userId){return count("SELECT COUNT(*) FROM accountant_profiles WHERE user_id=:user",Map.of("user",userId))>0;}
    public boolean canAccess(long userId,long propertyId){return count("SELECT COUNT(*) FROM accountant_property_assignments WHERE accountant_id=:user AND property_id=:property",Map.of("user",userId,"property",propertyId))>0;}
    public boolean permission(long userId,String column){if(!Set.of("can_issue_invoice","can_record_payment","can_review_proof","can_create_voucher","can_create_adjustment","can_close_period","can_reopen_period").contains(column))return false;return Boolean.TRUE.equals(jdbc.sql("SELECT "+column+" FROM accountant_profiles WHERE user_id=:user").param("user",userId).query(Boolean.class).optional().orElse(false));}
    public List<Map<String,Object>> properties(long userId){return rows("SELECT p.id,p.name,p.address FROM properties p JOIN accountant_property_assignments a ON a.property_id=p.id WHERE a.accountant_id=:user AND p.status='ACTIVE' ORDER BY p.name",Map.of("user",userId));}
    public Map<String,Object> profile(long userId){return one("SELECT u.id,u.email,u.full_name,u.phone,u.status,ap.* FROM users u JOIN accountant_profiles ap ON ap.user_id=u.id WHERE u.id=:user",Map.of("user",userId)).orElseThrow();}
    public int updateProfile(long userId,ProfileUpdate r){return jdbc.sql("UPDATE users SET email=:email,full_name=:name,phone=:phone WHERE id=:user").param("email",r.email().trim()).param("name",r.fullName().trim()).param("phone",blank(r.phone())).param("user",userId).update();}
    public boolean emailExists(long userId,String email){return count("SELECT COUNT(*) FROM users WHERE LOWER(email)=LOWER(:email) AND id<>:user",Map.of("email",email,"user",userId))>0;}
    public int preferences(long userId,Preferences r){return jdbc.sql("UPDATE accountant_profiles SET notify_payment=:payment,notify_overdue=:overdue,notify_reconciliation=:reconciliation,version=version+1 WHERE user_id=:user AND version=:version").param("payment",r.notifyPayment()).param("overdue",r.notifyOverdue()).param("reconciliation",r.notifyReconciliation()).param("user",userId).param("version",r.version()).update();}

    public Map<String,Object> dashboard(long userId,Long propertyId,String period){Map<String,Object> p=scope(userId,propertyId,period);String scope=(String)p.remove("scope");String invoiceScope=(String)p.remove("invoiceScope");String paymentScope=(String)p.remove("paymentScope");String voucherScope=(String)p.remove("voucherScope");Map<String,Object> result=new LinkedHashMap<>();String summary="SELECT (SELECT COALESCE(SUM(py.amount),0) FROM payments py WHERE "+paymentScope+" AND py.status='CONFIRMED' AND py.transaction_type='PAYMENT') collected,(SELECT COALESCE(SUM(v.amount),0) FROM payment_vouchers v WHERE "+voucherScope+" AND v.status='PAID') spent,(SELECT COALESCE(SUM(i.remaining_amount),0) FROM invoices i WHERE "+invoiceScope+" AND i.status<>'CANCELLED') debt,(SELECT COUNT(*) FROM tenant_payment_proofs tpp JOIN invoices i ON i.id=tpp.invoice_id WHERE "+invoiceScope+" AND tpp.status='PENDING') pending_proofs";result.put("properties",properties(userId));result.put("summary",one(summary,p).orElse(Map.of()));result.put("recentPayments",rows("SELECT py.id,py.receipt_code,py.amount,py.payment_method,py.paid_at,u.full_name tenant_name,i.code invoice_code FROM payments py JOIN invoices i ON i.id=py.invoice_id LEFT JOIN users u ON u.id=py.tenant_id JOIN accountant_property_assignments a ON a.property_id=py.property_id WHERE "+scope.replace("a.property_id","py.property_id")+" ORDER BY py.paid_at DESC LIMIT 8",p));result.put("overdueInvoices",rows("SELECT i.id,i.code,i.remaining_amount,i.due_date,u.full_name tenant_name,r.code room_code FROM invoices i JOIN users u ON u.id=i.tenant_id JOIN rooms r ON r.id=i.room_id WHERE "+invoiceScope+" AND i.remaining_amount>0 AND i.due_date<CURRENT_DATE AND i.status<>'CANCELLED' ORDER BY i.due_date LIMIT 8",p));result.put("ai",Map.of("available",false,"reason","Chưa cấu hình nhà cung cấp AI; hệ thống không tự động đối soát hoặc phê duyệt."));return result;}

    public Map<String,Object> pageInvoices(long userId,Long propertyId,String period,String status,String keyword,int page,int size){Map<String,Object> p=scope(userId,propertyId,period);String where=(String)p.remove("invoiceScope");if(status!=null&&!status.isBlank()){where+=" AND i.status=:status";p.put("status",status.toUpperCase());}if(keyword!=null&&!keyword.isBlank()){where+=" AND (LOWER(i.code) LIKE :keyword OR LOWER(u.full_name) LIKE :keyword OR LOWER(r.code) LIKE :keyword)";p.put("keyword","%"+keyword.trim().toLowerCase()+"%");}String joins=" FROM invoices i JOIN users u ON u.id=i.tenant_id JOIN rooms r ON r.id=i.room_id JOIN properties pr ON pr.id=i.property_id WHERE "+where;return page("SELECT i.id,i.code,i.billing_period,i.issue_date,i.due_date,i.total_amount,i.paid_amount,i.remaining_amount,i.status,i.version,u.full_name tenant_name,r.code room_code,pr.name property_name"+joins,"SELECT COUNT(*)"+joins,p,page,size,"i.created_at DESC");}
    public Optional<Map<String,Object>> invoice(long userId,long id,boolean lock){return one("SELECT i.*,p.name property_name,p.address property_address,r.code room_code,u.full_name tenant_name,u.email tenant_email,u.phone tenant_phone,c.code contract_code FROM invoices i JOIN properties p ON p.id=i.property_id JOIN rooms r ON r.id=i.room_id JOIN users u ON u.id=i.tenant_id JOIN contracts c ON c.id=i.contract_id JOIN accountant_property_assignments a ON a.property_id=i.property_id WHERE a.accountant_id=:user AND i.id=:id"+(lock?" FOR UPDATE":""),Map.of("user",userId,"id",id));}
    public List<Map<String,Object>> invoiceItems(long id){return rows("SELECT * FROM invoice_items WHERE invoice_id=:id ORDER BY display_order,id",Map.of("id",id));}
    public List<Map<String,Object>> invoicePayments(long id){return rows("SELECT * FROM payments WHERE invoice_id=:id ORDER BY paid_at DESC",Map.of("id",id));}
    public int issueInvoice(long id,long actor,long version){return jdbc.sql("UPDATE invoices SET status='ISSUED',issue_date=COALESCE(issue_date,CURRENT_DATE),issued_by=:actor,issued_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=:id AND status IN ('DRAFT','PENDING_REVIEW') AND version=:version").param("actor",actor).param("id",id).param("version",version).update();}

    public Map<String,Object> pagePayments(long userId,Long propertyId,String period,String status,String keyword,int page,int size){Map<String,Object> p=scope(userId,propertyId,period);String where=(String)p.remove("paymentScope");if(status!=null&&!status.isBlank()){where+=" AND py.status=:status";p.put("status",status.toUpperCase());}if(keyword!=null&&!keyword.isBlank()){where+=" AND (LOWER(py.receipt_code) LIKE :keyword OR LOWER(COALESCE(py.reference_code,'')) LIKE :keyword OR LOWER(u.full_name) LIKE :keyword)";p.put("keyword","%"+keyword.trim().toLowerCase()+"%");}String joins=" FROM payments py JOIN invoices i ON i.id=py.invoice_id LEFT JOIN users u ON u.id=py.tenant_id JOIN properties pr ON pr.id=py.property_id WHERE "+where;return page("SELECT py.*,i.code invoice_code,u.full_name tenant_name,pr.name property_name"+joins,"SELECT COUNT(*)"+joins,p,page,size,"py.paid_at DESC");}
    public Optional<Map<String,Object>> payment(long userId,long id,boolean lock){return one("SELECT py.*,i.code invoice_code,i.remaining_amount,u.full_name tenant_name,p.name property_name FROM payments py JOIN invoices i ON i.id=py.invoice_id LEFT JOIN users u ON u.id=py.tenant_id JOIN properties p ON p.id=py.property_id JOIN accountant_property_assignments a ON a.property_id=py.property_id WHERE a.accountant_id=:user AND py.id=:id"+(lock?" FOR UPDATE":""),Map.of("user",userId,"id",id));}
    public Optional<Map<String,Object>> paymentByKey(String key){return one("SELECT * FROM payments WHERE idempotency_key=:key",Map.of("key",key));}
    public long createPayment(Map<String,Object> invoice,PaymentCreate r,long actor,String key){KeyHolder k=new GeneratedKeyHolder();jdbc.sql("INSERT INTO payments(property_id,invoice_id,tenant_id,receipt_code,amount,payment_method,reference_code,idempotency_key,note,transaction_type,status,received_by,paid_at) VALUES(:property,:invoice,:tenant,CONCAT('PT-',DATE_FORMAT(NOW(),'%Y%m%d'),'-',LPAD(FLOOR(RAND()*999999),6,'0')),:amount,:method,:reference,:key,:note,'PAYMENT','CONFIRMED',:actor,:paidAt)").param("property",invoice.get("property_id")).param("invoice",invoice.get("id")).param("tenant",invoice.get("tenant_id")).param("amount",r.amount()).param("method",r.paymentMethod()).param("reference",blank(r.referenceCode())).param("key",key).param("note",blank(r.note())).param("actor",actor).param("paidAt",r.paidAt()).update(k,"id");return k.getKey().longValue();}
    public void allocation(long payment,long invoice,BigDecimal amount){jdbc.sql("INSERT INTO payment_allocations(payment_id,invoice_id,amount) VALUES(:payment,:invoice,:amount)").param("payment",payment).param("invoice",invoice).param("amount",amount).update();}
    public int applyPayment(long invoice,BigDecimal amount,long version){return jdbc.sql("UPDATE invoices SET paid_amount=paid_amount+:amount,remaining_amount=remaining_amount-:amount,status=CASE WHEN remaining_amount-:amount=0 THEN 'PAID' ELSE 'PARTIALLY_PAID' END,paid_at=CASE WHEN remaining_amount-:amount=0 THEN CURRENT_TIMESTAMP ELSE paid_at END,version=version+1 WHERE id=:invoice AND version=:version AND remaining_amount>=:amount AND status NOT IN ('DRAFT','CANCELLED','PAID')").param("amount",amount).param("invoice",invoice).param("version",version).update();}
    public long receipt(long payment,Map<String,Object> invoice,BigDecimal amount,long actor,String note){KeyHolder k=new GeneratedKeyHolder();jdbc.sql("INSERT INTO financial_receipts(receipt_code,payment_id,property_id,tenant_id,amount,issued_by,note) VALUES(CONCAT('BL-',DATE_FORMAT(NOW(),'%Y%m%d'),'-',LPAD(FLOOR(RAND()*999999),6,'0')),:payment,:property,:tenant,:amount,:actor,:note)").param("payment",payment).param("property",invoice.get("property_id")).param("tenant",invoice.get("tenant_id")).param("amount",amount).param("actor",actor).param("note",blank(note)).update(k,"id");return k.getKey().longValue();}
    public int reversePayment(long id,long actor,String reason){return jdbc.sql("UPDATE payments SET status='REVERSED',reversal_reason=:reason,reversed_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=:id AND status='CONFIRMED'").param("reason",reason).param("id",id).update();}
    public int reverseInvoice(long invoice,BigDecimal amount){return jdbc.sql("UPDATE invoices SET paid_amount=GREATEST(paid_amount-:amount,0),remaining_amount=LEAST(total_amount,remaining_amount+:amount),status=CASE WHEN paid_amount-:amount<=0 THEN 'ISSUED' ELSE 'PARTIALLY_PAID' END,paid_at=NULL,version=version+1 WHERE id=:invoice").param("amount",amount).param("invoice",invoice).update();}
    public void reverseAllocation(long payment){jdbc.sql("UPDATE payment_allocations SET status='REVERSED',reversed_at=CURRENT_TIMESTAMP WHERE payment_id=:payment AND status='CONFIRMED'").param("payment",payment).update();}

    public Map<String,Object> pageProofs(long userId,Long propertyId,String status,int page,int size){Map<String,Object> p=scope(userId,propertyId,LocalDate.now().toString().substring(0,7));String where=(String)p.remove("proofScope");if(status!=null&&!status.isBlank()){where+=" AND tpp.status=:status";p.put("status",status.toUpperCase());}String joins=" FROM tenant_payment_proofs tpp JOIN invoices i ON i.id=tpp.invoice_id JOIN users u ON u.id=tpp.tenant_id JOIN properties pr ON pr.id=i.property_id WHERE "+where;return page("SELECT tpp.id,tpp.invoice_id,tpp.amount,tpp.transferred_at,tpp.bank_name,tpp.transaction_reference,tpp.original_name,tpp.mime_type,tpp.file_size,tpp.note,tpp.status,tpp.rejection_reason,tpp.created_at,i.code invoice_code,u.full_name tenant_name,pr.name property_name"+joins,"SELECT COUNT(*)"+joins,p,page,size,"tpp.created_at DESC");}
    public Optional<Map<String,Object>> proof(long userId,long id,boolean lock){return one("SELECT tpp.*,i.property_id,i.tenant_id,i.remaining_amount,i.version invoice_version,i.status invoice_status FROM tenant_payment_proofs tpp JOIN invoices i ON i.id=tpp.invoice_id JOIN accountant_property_assignments a ON a.property_id=i.property_id WHERE a.accountant_id=:user AND tpp.id=:id"+(lock?" FOR UPDATE":""),Map.of("user",userId,"id",id));}
    public int approveProof(long id,long actor){return jdbc.sql("UPDATE tenant_payment_proofs SET status='APPROVED',reviewed_by=:actor,reviewed_at=CURRENT_TIMESTAMP,rejection_reason=NULL WHERE id=:id AND status='PENDING'").param("actor",actor).param("id",id).update();}
    public int rejectProof(long id,long actor,String reason){return jdbc.sql("UPDATE tenant_payment_proofs SET status='REJECTED',reviewed_by=:actor,reviewed_at=CURRENT_TIMESTAMP,rejection_reason=:reason WHERE id=:id AND status='PENDING'").param("actor",actor).param("reason",reason).param("id",id).update();}

    public Map<String,Object> pageDebts(long userId,Long propertyId,String keyword,int page,int size){Map<String,Object> p=scope(userId,propertyId,LocalDate.now().toString().substring(0,7));String where=(String)p.remove("baseInvoiceScope");where+=" AND i.remaining_amount>0 AND i.status<>'CANCELLED'";if(keyword!=null&&!keyword.isBlank()){where+=" AND (LOWER(u.full_name) LIKE :keyword OR LOWER(i.code) LIKE :keyword OR LOWER(r.code) LIKE :keyword)";p.put("keyword","%"+keyword.trim().toLowerCase()+"%");}String joins=" FROM invoices i JOIN users u ON u.id=i.tenant_id JOIN rooms r ON r.id=i.room_id JOIN properties pr ON pr.id=i.property_id WHERE "+where;return page("SELECT i.id,i.code,i.tenant_id,u.full_name tenant_name,u.phone,r.code room_code,pr.name property_name,i.due_date,i.remaining_amount,DATEDIFF(CURRENT_DATE,i.due_date) overdue_days,CASE WHEN DATEDIFF(CURRENT_DATE,i.due_date)<=0 THEN 'CURRENT' WHEN DATEDIFF(CURRENT_DATE,i.due_date)<=30 THEN '1_30' WHEN DATEDIFF(CURRENT_DATE,i.due_date)<=60 THEN '31_60' WHEN DATEDIFF(CURRENT_DATE,i.due_date)<=90 THEN '61_90' ELSE '90_PLUS' END aging_bucket"+joins,"SELECT COUNT(*)"+joins,p,page,size,"i.due_date ASC");}
    public Map<String,Object> pageTenantDebts(long userId,long tenantId,Long propertyId,int page,int size){Map<String,Object> p=scope(userId,propertyId,LocalDate.now().toString().substring(0,7));String where=(String)p.remove("baseInvoiceScope");where+=" AND i.tenant_id=:tenant AND i.remaining_amount>0 AND i.status<>'CANCELLED'";p.put("tenant",tenantId);String joins=" FROM invoices i JOIN users u ON u.id=i.tenant_id JOIN rooms r ON r.id=i.room_id JOIN properties pr ON pr.id=i.property_id WHERE "+where;Map<String,Object> result=page("SELECT i.id,i.code,i.tenant_id,u.full_name tenant_name,u.phone,u.email,r.code room_code,pr.name property_name,i.due_date,i.total_amount,i.paid_amount,i.remaining_amount,DATEDIFF(CURRENT_DATE,i.due_date) overdue_days"+joins,"SELECT COUNT(*)"+joins,p,page,size,"i.due_date ASC");result.put("reminders",rows("SELECT dr.* FROM debt_reminders dr JOIN invoices i ON i.id=dr.invoice_id WHERE i.tenant_id=:tenant AND "+where.replace("i.tenant_id=:tenant AND ","")+" ORDER BY dr.sent_at DESC",p));result.put("promises",rows("SELECT pp.* FROM payment_promises pp JOIN invoices i ON i.id=pp.invoice_id WHERE i.tenant_id=:tenant AND "+where.replace("i.tenant_id=:tenant AND ","")+" ORDER BY pp.created_at DESC",p));return result;}
    public void reminder(long invoice,long actor,Reminder r){jdbc.sql("INSERT INTO debt_reminders(invoice_id,channel,recipient,message,sent_by) VALUES(:invoice,:channel,:recipient,:message,:actor)").param("invoice",invoice).param("channel",r.channel()).param("recipient",r.recipient()).param("message",r.message()).param("actor",actor).update();}
    public void promise(long invoice,long actor,PromiseCreate r){jdbc.sql("INSERT INTO payment_promises(invoice_id,promised_amount,promised_date,note,created_by) VALUES(:invoice,:amount,:date,:note,:actor)").param("invoice",invoice).param("amount",r.amount()).param("date",r.promisedDate()).param("note",blank(r.note())).param("actor",actor).update();}

    public Map<String,Object> pageDeposits(long userId,Long propertyId,int page,int size){Map<String,Object> p=new HashMap<>();p.put("user",userId);String where="a.accountant_id=:user";if(propertyId!=null){where+=" AND d.property_id=:property";p.put("property",propertyId);}String joins=" FROM tenant_deposits d JOIN accountant_property_assignments a ON a.property_id=d.property_id JOIN contracts c ON c.id=d.contract_id JOIN rooms r ON r.id=c.room_id JOIN users u ON u.id=d.tenant_id JOIN properties pr ON pr.id=d.property_id WHERE "+where;return page("SELECT d.*,c.code contract_code,r.code room_code,u.full_name tenant_name,pr.name property_name"+joins,"SELECT COUNT(*)"+joins,p,page,size,"d.id DESC");}
    public Optional<Map<String,Object>> deposit(long userId,long id,boolean lock){return one("SELECT d.* FROM tenant_deposits d JOIN accountant_property_assignments a ON a.property_id=d.property_id WHERE a.accountant_id=:user AND d.id=:id"+(lock?" FOR UPDATE":""),Map.of("user",userId,"id",id));}
    public int applyDeposit(long id,DepositTransaction r){BigDecimal signed="COLLECT".equals(r.type())?r.amount():r.amount().negate();return jdbc.sql("UPDATE tenant_deposits SET balance_amount=balance_amount+:signed,status=CASE WHEN balance_amount+:signed=0 THEN 'SETTLED' WHEN balance_amount+:signed>=required_amount THEN 'HELD' ELSE 'PARTIAL' END,version=version+1 WHERE id=:id AND version=:version AND balance_amount+:signed>=0").param("signed",signed).param("id",id).param("version",r.version()).update();}
    public void depositTransaction(long id,long actor,DepositTransaction r){jdbc.sql("INSERT INTO deposit_transactions(deposit_id,transaction_code,transaction_type,amount,reason,reference_code,transacted_by) VALUES(:deposit,CONCAT('CD-',DATE_FORMAT(NOW(),'%Y%m%d'),'-',LPAD(FLOOR(RAND()*999999),6,'0')),:type,:amount,:reason,:reference,:actor)").param("deposit",id).param("type",r.type()).param("amount",r.amount()).param("reason",blank(r.reason())).param("reference",blank(r.referenceCode())).param("actor",actor).update();}

    public Map<String,Object> pageVouchers(long userId,Long propertyId,String status,int page,int size){Map<String,Object> p=new HashMap<>();p.put("user",userId);String where="a.accountant_id=:user";if(propertyId!=null){where+=" AND v.property_id=:property";p.put("property",propertyId);}if(status!=null&&!status.isBlank()){where+=" AND v.status=:status";p.put("status",status.toUpperCase());}String joins=" FROM payment_vouchers v JOIN accountant_property_assignments a ON a.property_id=v.property_id JOIN properties pr ON pr.id=v.property_id WHERE "+where;return page("SELECT v.*,pr.name property_name"+joins,"SELECT COUNT(*)"+joins,p,page,size,"v.created_at DESC");}
    public long voucher(long actor,VoucherCreate r){KeyHolder k=new GeneratedKeyHolder();jdbc.sql("INSERT INTO payment_vouchers(voucher_code,property_id,payee_name,amount,expense_category,payment_method,voucher_date,description,created_by) VALUES(CONCAT('PC-',DATE_FORMAT(NOW(),'%Y%m%d'),'-',LPAD(FLOOR(RAND()*999999),6,'0')),:property,:payee,:amount,:category,:method,:date,:description,:actor)").param("property",r.propertyId()).param("payee",r.payeeName()).param("amount",r.amount()).param("category",r.category()).param("method",r.paymentMethod()).param("date",r.voucherDate()).param("description",r.description()).param("actor",actor).update(k,"id");return k.getKey().longValue();}
    public Optional<Map<String,Object>> voucher(long userId,long id){return one("SELECT v.*,p.name property_name FROM payment_vouchers v JOIN properties p ON p.id=v.property_id JOIN accountant_property_assignments a ON a.property_id=v.property_id WHERE a.accountant_id=:user AND v.id=:id",Map.of("user",userId,"id",id));}
    public int submitVoucher(long userId,long id,long version){return jdbc.sql("UPDATE payment_vouchers SET status='PENDING_APPROVAL',submitted_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=:id AND created_by=:user AND version=:version AND status='DRAFT'").param("id",id).param("user",userId).param("version",version).update();}
    public Map<String,Object> pageOtherIncome(long userId,Long propertyId,String period,int page,int size){Map<String,Object> p=scope(userId,propertyId,period);String where=(String)p.remove("incomeScope");String joins=" FROM other_income oi JOIN properties pr ON pr.id=oi.property_id WHERE "+where;return page("SELECT oi.*,pr.name property_name"+joins,"SELECT COUNT(*)"+joins,p,page,size,"oi.income_date DESC,oi.id DESC");}
    public long otherIncome(long actor,OtherIncomeCreate r){KeyHolder k=new GeneratedKeyHolder();jdbc.sql("INSERT INTO other_income(property_id,income_code,category,amount,income_date,description,payment_method,created_by) VALUES(:property,CONCAT('TK-',DATE_FORMAT(NOW(),'%Y%m%d'),'-',LPAD(FLOOR(RAND()*999999),6,'0')),:category,:amount,:date,:description,:method,:actor)").param("property",r.propertyId()).param("category",r.category()).param("amount",r.amount()).param("date",r.incomeDate()).param("description",r.description()).param("method",r.paymentMethod()).param("actor",actor).update(k,"id");return k.getKey().longValue();}
    public Optional<Map<String,Object>> otherIncome(long userId,long id){return one("SELECT oi.*,p.name property_name FROM other_income oi JOIN properties p ON p.id=oi.property_id JOIN accountant_property_assignments a ON a.property_id=oi.property_id WHERE a.accountant_id=:user AND oi.id=:id",Map.of("user",userId,"id",id));}

    public Map<String,Object> periods(long userId,Long propertyId){Map<String,Object> p=new HashMap<>();p.put("user",userId);String where="a.accountant_id=:user";if(propertyId!=null){where+=" AND ap.property_id=:property";p.put("property",propertyId);}return Map.of("content",rows("SELECT ap.*,pr.name property_name FROM accounting_periods ap JOIN properties pr ON pr.id=ap.property_id JOIN accountant_property_assignments a ON a.property_id=ap.property_id WHERE "+where+" ORDER BY ap.start_date DESC",p));}
    public Optional<Map<String,Object>> period(long userId,long id,boolean lock){return one("SELECT ap.* FROM accounting_periods ap JOIN accountant_property_assignments a ON a.property_id=ap.property_id WHERE a.accountant_id=:user AND ap.id=:id"+(lock?" FOR UPDATE":""),Map.of("user",userId,"id",id));}
    public int closePeriod(long id,long actor,long version,String note){return jdbc.sql("UPDATE accounting_periods SET status='CLOSED',closed_by=:actor,closed_at=CURRENT_TIMESTAMP,close_note=:note,version=version+1 WHERE id=:id AND status='OPEN' AND version=:version").param("actor",actor).param("note",blank(note)).param("id",id).param("version",version).update();}
    public int reopenPeriod(long id,long actor,long version,String reason){return jdbc.sql("UPDATE accounting_periods SET status='OPEN',reopened_by=:actor,reopened_at=CURRENT_TIMESTAMP,reopen_reason=:reason,version=version+1 WHERE id=:id AND status='CLOSED' AND version=:version").param("actor",actor).param("reason",reason).param("id",id).param("version",version).update();}
    public boolean locked(long propertyId,LocalDate date){return count("SELECT COUNT(*) FROM accounting_periods WHERE property_id=:property AND :date BETWEEN start_date AND end_date AND status='CLOSED'",Map.of("property",propertyId,"date",date))>0;}

    public Map<String,Object> books(long userId,Long propertyId,String period,String type,int page,int size){Map<String,Object> p=scope(userId,propertyId,period);String payment=(String)p.remove("paymentScope");String voucher=(String)p.remove("voucherScope");String income=(String)p.remove("incomeScope");String sql="SELECT * FROM (SELECT py.id,py.paid_at occurred_at,'RECEIPT' entry_type,py.receipt_code code,py.amount debit,0 credit,py.payment_method method,py.note description FROM payments py WHERE "+payment+" AND py.status='CONFIRMED' UNION ALL SELECT v.id,CAST(v.voucher_date AS DATETIME),'PAYMENT',v.voucher_code,0,v.amount,v.payment_method,v.description FROM payment_vouchers v WHERE "+voucher+" AND v.status='PAID' UNION ALL SELECT oi.id,CAST(oi.income_date AS DATETIME),'OTHER_INCOME',oi.income_code,oi.amount,0,oi.payment_method,oi.description FROM other_income oi WHERE "+income+" AND oi.status='CONFIRMED') b";if("CASH".equalsIgnoreCase(type))sql+=" WHERE method='CASH'";else if("BANK".equalsIgnoreCase(type))sql+=" WHERE method<>'CASH'";long total=rows(sql,p).size();p.put("limit",size);p.put("offset",page*size);List<Map<String,Object>> content=rows(sql+" ORDER BY occurred_at DESC LIMIT :limit OFFSET :offset",p);return pageMap(content,page,size,total);}
    public Map<String,Object> report(long userId,Long propertyId,String period){Map<String,Object> d=dashboard(userId,propertyId,period);Map<String,Object> p=scope(userId,propertyId,period);String invoice=(String)p.remove("invoiceScope");d.put("aging",rows("SELECT CASE WHEN DATEDIFF(CURRENT_DATE,due_date)<=0 THEN 'CURRENT' WHEN DATEDIFF(CURRENT_DATE,due_date)<=30 THEN '1_30' WHEN DATEDIFF(CURRENT_DATE,due_date)<=60 THEN '31_60' WHEN DATEDIFF(CURRENT_DATE,due_date)<=90 THEN '61_90' ELSE '90_PLUS' END bucket,COUNT(*) invoice_count,COALESCE(SUM(remaining_amount),0) amount FROM invoices i WHERE "+invoice+" AND remaining_amount>0 AND status<>'CANCELLED' GROUP BY bucket ORDER BY bucket",p));return d;}
    public List<Map<String,Object>> notifications(long userId){return rows("SELECT id,title,content,type,read_at,created_at FROM notifications WHERE user_id=:user ORDER BY created_at DESC LIMIT 100",Map.of("user",userId));}
    public int readNotification(long userId,long id){return jdbc.sql("UPDATE notifications SET read_at=COALESCE(read_at,CURRENT_TIMESTAMP) WHERE id=:id AND user_id=:user").param("id",id).param("user",userId).update();}
    public void audit(Long property,long actor,String type,long id,String action,String reason){jdbc.sql("INSERT INTO financial_audit_logs(property_id,actor_id,entity_type,entity_id,action,reason) VALUES(:property,:actor,:type,:id,:action,:reason)").param("property",property).param("actor",actor).param("type",type).param("id",id).param("action",action).param("reason",blank(reason)).update();}

    private Map<String,Object> scope(long userId,Long propertyId,String period){Map<String,Object> p=new HashMap<>();p.put("user",userId);p.put("period",period==null||period.isBlank()?LocalDate.now().toString().substring(0,7):period);String a="a.accountant_id=:user",i="EXISTS(SELECT 1 FROM accountant_property_assignments a2 WHERE a2.accountant_id=:user AND a2.property_id=i.property_id)",py="EXISTS(SELECT 1 FROM accountant_property_assignments a2 WHERE a2.accountant_id=:user AND a2.property_id=py.property_id) AND DATE_FORMAT(py.paid_at,'%Y-%m')=:period",proof="EXISTS(SELECT 1 FROM accountant_property_assignments a2 WHERE a2.accountant_id=:user AND a2.property_id=i.property_id)";String v="EXISTS(SELECT 1 FROM accountant_property_assignments a2 WHERE a2.accountant_id=:user AND a2.property_id=v.property_id) AND DATE_FORMAT(v.voucher_date,'%Y-%m')=:period",oi="EXISTS(SELECT 1 FROM accountant_property_assignments a2 WHERE a2.accountant_id=:user AND a2.property_id=oi.property_id) AND DATE_FORMAT(oi.income_date,'%Y-%m')=:period";if(propertyId!=null){p.put("property",propertyId);a+=" AND a.property_id=:property";i+=" AND i.property_id=:property";py+=" AND py.property_id=:property";proof+=" AND i.property_id=:property";v+=" AND v.property_id=:property";oi+=" AND oi.property_id=:property";}p.put("scope",a);p.put("baseInvoiceScope",i);p.put("invoiceScope",i+" AND DATE_FORMAT(i.billing_period,'%Y-%m')=:period");p.put("paymentScope",py);p.put("proofScope",proof);p.put("voucherScope",v);p.put("incomeScope",oi);return p;}
    private Map<String,Object> page(String select,String countSql,Map<String,Object> params,int page,int size,String order){long total=count(countSql,params);Map<String,Object> p=new HashMap<>(params);p.put("limit",size);p.put("offset",page*size);return pageMap(rows(select+" ORDER BY "+order+" LIMIT :limit OFFSET :offset",p),page,size,total);}
    private Map<String,Object> pageMap(List<Map<String,Object>> content,int page,int size,long total){Map<String,Object> r=new LinkedHashMap<>();r.put("content",content);r.put("page",page);r.put("size",size);r.put("totalElements",total);r.put("totalPages",(int)Math.ceil(total/(double)size));return r;}
    private long count(String sql,Map<String,Object> params){return jdbc.sql(sql).params(params).query(Long.class).single();}
    private List<Map<String,Object>> rows(String sql,Map<String,Object> params){return jdbc.sql(sql).params(params).query(AccountantPortalRepository::map).list();}
    private Optional<Map<String,Object>> one(String sql,Map<String,Object> params){return jdbc.sql(sql).params(params).query(AccountantPortalRepository::map).optional();}
    private static Map<String,Object> map(ResultSet r,int row)throws SQLException{Map<String,Object> m=new LinkedHashMap<>();ResultSetMetaData md=r.getMetaData();for(int i=1;i<=md.getColumnCount();i++)m.put(md.getColumnLabel(i),r.getObject(i));return m;}
    private static String blank(String value){return value==null||value.isBlank()?null:value.trim();}
}
