package com.thangit.boardinghouse.repository;

import com.thangit.boardinghouse.domain.auth.RoleCode;
import com.thangit.boardinghouse.dto.request.invoice.AdminInvoiceRequests.AdditionalItem;
import com.thangit.boardinghouse.dto.response.invoice.AdminInvoiceResponses.*;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

@Repository
public class AdminInvoiceRepository {
    private final JdbcClient jdbc;
    public AdminInvoiceRepository(JdbcClient jdbc){this.jdbc=jdbc;}
    private String scope(RoleCode role,String p){return role==RoleCode.OWNER?p+".owner_id=:userId":"EXISTS(SELECT 1 FROM property_managers pm WHERE pm.property_id="+p+".id AND pm.manager_id=:userId)";}
    public boolean canAccess(long userId,RoleCode role,long propertyId){return jdbc.sql("SELECT COUNT(*) FROM properties p WHERE p.id=:id AND "+scope(role,"p")).param("id",propertyId).param("userId",userId).query(Long.class).single()>0;}
    public List<Option> properties(long userId,RoleCode role){return jdbc.sql("SELECT p.id,p.name FROM properties p WHERE "+scope(role,"p")+" ORDER BY p.name").param("userId",userId).query((r,n)->new Option(r.getLong(1),r.getString(2),null)).list();}
    public List<Option> buildings(long userId,RoleCode role){return jdbc.sql("SELECT b.id,b.name,b.property_id FROM buildings b JOIN properties p ON p.id=b.property_id WHERE "+scope(role,"p")+" ORDER BY p.name,b.display_order").param("userId",userId).query((r,n)->new Option(r.getLong(1),r.getString(2),r.getLong(3))).list();}
    public List<Option> floors(long userId,RoleCode role){return jdbc.sql("SELECT f.id,f.name,f.building_id FROM floors f JOIN buildings b ON b.id=f.building_id JOIN properties p ON p.id=b.property_id WHERE "+scope(role,"p")+" ORDER BY b.display_order,f.display_order").param("userId",userId).query((r,n)->new Option(r.getLong(1),r.getString(2),r.getLong(3))).list();}
    public List<Option> rooms(long userId,RoleCode role){return jdbc.sql("SELECT r.id,CONCAT(r.code,' · ',COALESCE(r.name,'')),r.floor_id FROM rooms r JOIN properties p ON p.id=r.property_id WHERE "+scope(role,"p")+" ORDER BY p.name,r.code").param("userId",userId).query((r,n)->new Option(r.getLong(1),r.getString(2),nullableLong(r,3))).list();}
    public List<Option> contracts(long userId,RoleCode role){return jdbc.sql("SELECT c.id,CONCAT(c.code,' · ',u.full_name),c.room_id FROM contracts c JOIN rooms r ON r.id=c.room_id JOIN properties p ON p.id=r.property_id JOIN users u ON u.id=c.tenant_id WHERE c.status='ACTIVE' AND "+scope(role,"p")+" ORDER BY c.code").param("userId",userId).query((r,n)->new Option(r.getLong(1),r.getString(2),r.getLong(3))).list();}

    private record Filter(String where,Map<String,Object> params){}
    private Filter filters(long userId,RoleCode role,Long propertyId,Long buildingId,Long floorId,Long roomId,String keyword,String period,String status,Boolean overdue,BigDecimal min,BigDecimal max){
        StringBuilder w=new StringBuilder(scope(role,"p"));Map<String,Object> x=new HashMap<>();x.put("userId",userId);
        if(propertyId!=null){w.append(" AND p.id=:propertyId");x.put("propertyId",propertyId);}if(buildingId!=null){w.append(" AND r.building_id=:buildingId");x.put("buildingId",buildingId);}if(floorId!=null){w.append(" AND r.floor_id=:floorId");x.put("floorId",floorId);}if(roomId!=null){w.append(" AND r.id=:roomId");x.put("roomId",roomId);}
        if(period!=null&&!period.isBlank()){w.append(" AND DATE_FORMAT(i.billing_period,'%Y-%m')=:period");x.put("period",period);}if(status!=null&&!status.isBlank()){w.append(" AND ").append(effectiveStatus()).append("=:status");x.put("status",status.toUpperCase());}
        if(Boolean.TRUE.equals(overdue))w.append(" AND i.due_date<CURRENT_DATE AND i.remaining_amount>0 AND i.status<>'CANCELLED'");if(min!=null){w.append(" AND i.total_amount>=:minimum");x.put("minimum",min);}if(max!=null){w.append(" AND i.total_amount<=:maximum");x.put("maximum",max);}
        if(keyword!=null&&!keyword.isBlank()){w.append(" AND (LOWER(i.code) LIKE :keyword OR LOWER(r.code) LIKE :keyword OR LOWER(p.name) LIKE :keyword OR LOWER(u.full_name) LIKE :keyword OR LOWER(COALESCE(u.phone,'')) LIKE :keyword OR LOWER(c.code) LIKE :keyword)");x.put("keyword","%"+keyword.trim().toLowerCase()+"%");}return new Filter(w.toString(),x);
    }
    private String effectiveStatus(){return "CASE WHEN i.status IN ('ISSUED','UNPAID','PARTIALLY_PAID') AND i.remaining_amount>0 AND i.due_date<CURRENT_DATE THEN 'OVERDUE' ELSE i.status END";}
    private String joins(){return " FROM invoices i JOIN contracts c ON c.id=i.contract_id JOIN rooms r ON r.id=COALESCE(i.room_id,c.room_id) JOIN properties p ON p.id=r.property_id JOIN users u ON u.id=c.tenant_id LEFT JOIN users cb ON cb.id=i.created_by ";}
    public Summary summary(long userId,RoleCode role,Long propertyId,String period){Filter f=filters(userId,role,propertyId,null,null,null,null,period,null,null,null,null);return jdbc.sql("SELECT COALESCE(SUM(CASE WHEN i.status<>'CANCELLED' THEN i.total_amount ELSE 0 END),0) total,COALESCE(SUM(CASE WHEN i.status<>'CANCELLED' THEN i.paid_amount ELSE 0 END),0) paid,COALESCE(SUM(CASE WHEN i.status<>'CANCELLED' THEN i.remaining_amount ELSE 0 END),0) debt,SUM(i.status='DRAFT') drafts,SUM(i.status IN ('ISSUED','UNPAID')) unpaid,SUM(i.status='PARTIALLY_PAID') partial,SUM(i.status='PAID') paid_count,SUM(i.due_date<CURRENT_DATE AND i.remaining_amount>0 AND i.status<>'CANCELLED') overdue "+joins()+" WHERE "+f.where()).params(f.params()).query((r,n)->{BigDecimal total=r.getBigDecimal("total"),paid=r.getBigDecimal("paid");return new Summary(total,paid,r.getBigDecimal("debt"),total.signum()==0?BigDecimal.ZERO:paid.multiply(BigDecimal.valueOf(100)).divide(total,2,java.math.RoundingMode.HALF_UP),r.getLong("drafts"),r.getLong("unpaid"),r.getLong("partial"),r.getLong("paid_count"),r.getLong("overdue"));}).single();}
    public Page<InvoiceRow> list(long userId,RoleCode role,Long propertyId,Long buildingId,Long floorId,Long roomId,String keyword,String period,String status,Boolean overdue,BigDecimal min,BigDecimal max,String sort,int page,int size){Filter f=filters(userId,role,propertyId,buildingId,floorId,roomId,keyword,period,status,overdue,min,max);long total=jdbc.sql("SELECT COUNT(*)"+joins()+" WHERE "+f.where()).params(f.params()).query(Long.class).single();String order=switch(sort==null?"":sort){case"oldest"->"i.created_at ASC";case"due"->"i.due_date ASC";case"amount"->"i.total_amount DESC";case"debt"->"i.remaining_amount DESC";default->"i.created_at DESC";};Map<String,Object>x=new HashMap<>(f.params());x.put("limit",size);x.put("offset",page*size);List<InvoiceRow> rows=jdbc.sql("SELECT i.id,i.code,DATE_FORMAT(i.billing_period,'%m/%Y') period,p.id property_id,p.name property_name,r.id room_id,r.code room_code,r.building_name,r.floor_name,u.id tenant_id,u.full_name,u.phone,c.id contract_id,c.code contract_code,i.issue_date,i.due_date,i.total_amount,i.paid_amount,i.remaining_amount,"+effectiveStatus()+" effective_status,i.is_automated,i.has_adjustment,i.version,i.created_at,cb.id creator_id,cb.full_name creator_name"+joins()+" WHERE "+f.where()+" ORDER BY "+order+" LIMIT :limit OFFSET :offset").params(x).query((r,n)->row(r)).list();return new Page<>(rows,page,size,total,(int)Math.ceil(total/(double)size));}
    public Optional<Map<String,Object>> invoice(long id,boolean lock){return jdbc.sql("SELECT i.*,p.name property_name,p.address property_address,r.code room_code,r.building_name,r.floor_name,u.full_name tenant_name,u.phone tenant_phone,u.email tenant_email,c.code contract_code,c.start_date contract_start,c.end_date contract_end FROM invoices i JOIN contracts c ON c.id=i.contract_id JOIN rooms r ON r.id=COALESCE(i.room_id,c.room_id) JOIN properties p ON p.id=r.property_id JOIN users u ON u.id=c.tenant_id WHERE i.id=:id"+(lock?" FOR UPDATE":"")).param("id",id).query(AdminInvoiceRepository::map).optional();}
    public Optional<Map<String,Object>> contractForRoom(long roomId,long contractId){return jdbc.sql("SELECT c.*,r.property_id,r.code room_code,r.monthly_rent,u.full_name tenant_name,u.phone tenant_phone FROM contracts c JOIN rooms r ON r.id=c.room_id JOIN users u ON u.id=c.tenant_id WHERE c.id=:contract AND r.id=:room").param("contract",contractId).param("room",roomId).query(AdminInvoiceRepository::map).optional();}
    public Optional<Map<String,Object>> activeContract(long roomId){return jdbc.sql("SELECT c.*,r.property_id,r.code room_code,r.monthly_rent,u.full_name tenant_name FROM contracts c JOIN rooms r ON r.id=c.room_id JOIN users u ON u.id=c.tenant_id WHERE r.id=:room AND c.status='ACTIVE' AND CURRENT_DATE BETWEEN c.start_date AND c.end_date ORDER BY c.start_date DESC LIMIT 1").param("room",roomId).query(AdminInvoiceRepository::map).optional();}
    public boolean duplicate(long contractId,LocalDate period,Long excluded){return jdbc.sql("SELECT COUNT(*) FROM invoices WHERE contract_id=:contract AND billing_period=:period AND status<>'CANCELLED' AND (:excluded IS NULL OR id<>:excluded)").param("contract",contractId).param("period",period).param("excluded",excluded).query(Long.class).single()>0;}
    public Optional<Map<String,Object>> utility(long contractId,LocalDate period){return jdbc.sql("SELECT * FROM utility_readings WHERE contract_id=:contract AND billing_period=:period").param("contract",contractId).param("period",period).query(AdminInvoiceRepository::map).optional();}
    public List<Map<String,Object>> services(long contractId,LocalDate end){return jdbc.sql("SELECT * FROM contract_services WHERE contract_id=:contract AND effective_date<=:end ORDER BY name").param("contract",contractId).param("end",end).query(AdminInvoiceRepository::map).list();}
    public BigDecimal previousDebt(long contractId,LocalDate period){return jdbc.sql("SELECT COALESCE(SUM(remaining_amount),0) FROM invoices WHERE contract_id=:contract AND billing_period<:period AND status NOT IN ('DRAFT','CANCELLED')").param("contract",contractId).param("period",period).query(BigDecimal.class).single();}
    public long createInvoice(long propertyId,long roomId,long contractId,long tenantId,String code,LocalDate period,LocalDate start,LocalDate end,LocalDate issue,LocalDate due,BigDecimal subtotal,BigDecimal discount,BigDecimal debt,BigDecimal lateFee,BigDecimal total,String status,String note,long actor,boolean automated){KeyHolder k=new GeneratedKeyHolder();jdbc.sql("INSERT INTO invoices(property_id,room_id,contract_id,tenant_id,code,billing_period,period_start_date,period_end_date,issue_date,due_date,total_amount,subtotal_amount,discount_amount,previous_debt_amount,late_fee_amount,paid_amount,remaining_amount,status,note,is_automated,created_by,issued_by,issued_at) VALUES(:property,:room,:contract,:tenant,:code,:period,:start,:end,:issue,:due,:total,:subtotal,:discount,:debt,:lateFee,0,:total,:status,:note,:automated,:actor,"+("DRAFT".equals(status)?"NULL,NULL":":actor,CURRENT_TIMESTAMP")+")").param("property",propertyId).param("room",roomId).param("contract",contractId).param("tenant",tenantId).param("code",code).param("period",period).param("start",start).param("end",end).param("issue",issue).param("due",due).param("total",total).param("subtotal",subtotal).param("discount",discount).param("debt",debt).param("lateFee",lateFee).param("status",status).param("note",blank(note)).param("automated",automated).param("actor",actor).update(k,"id");return k.getKey().longValue();}
    public void addItem(long invoiceId,String type,String code,String name,String description,BigDecimal qty,String unit,BigDecimal price,BigDecimal amount,String source,Long sourceId,int order){jdbc.sql("INSERT INTO invoice_items(invoice_id,item_type,item_code,name,description,quantity,unit,unit_price,amount,source_type,source_id,display_order) VALUES(:invoice,:type,:code,:name,:description,:qty,:unit,:price,:amount,:source,:sourceId,:order)").param("invoice",invoiceId).param("type",type).param("code",code).param("name",name).param("description",description).param("qty",qty).param("unit",unit).param("price",price).param("amount",amount).param("source",source).param("sourceId",sourceId).param("order",order).update();}
    public List<Item> items(long id){return jdbc.sql("SELECT * FROM invoice_items WHERE invoice_id=:id ORDER BY display_order,id").param("id",id).query((r,n)->new Item(r.getLong("id"),r.getString("item_type"),r.getString("name"),r.getString("description"),r.getBigDecimal("quantity"),r.getString("unit"),r.getBigDecimal("unit_price"),r.getBigDecimal("amount"),r.getString("source_type"),nullableLong(r,"source_id"))).list();}
    public List<Payment> payments(long id){return jdbc.sql("SELECT py.*,u.full_name FROM payments py LEFT JOIN users u ON u.id=py.received_by WHERE py.invoice_id=:id ORDER BY py.paid_at DESC").param("id",id).query((r,n)->new Payment(r.getLong("id"),r.getString("receipt_code"),r.getBigDecimal("amount"),r.getString("payment_method"),r.getString("reference_code"),r.getString("note"),r.getString("status"),r.getString("full_name"),r.getObject("paid_at",LocalDateTime.class))).list();}
    public List<AdjustmentItem> adjustments(long id){return jdbc.sql("SELECT a.*,u.full_name FROM invoice_adjustments a LEFT JOIN users u ON u.id=a.requested_by WHERE a.invoice_id=:id ORDER BY a.created_at DESC").param("id",id).query((r,n)->new AdjustmentItem(r.getLong("id"),r.getString("adjustment_code"),r.getString("adjustment_type"),r.getBigDecimal("amount"),r.getString("reason"),r.getString("status"),r.getString("full_name"),r.getObject("created_at",LocalDateTime.class))).list();}
    public List<NotificationItem> notifications(long id){return jdbc.sql("SELECT * FROM invoice_notification_logs WHERE invoice_id=:id ORDER BY created_at DESC").param("id",id).query((r,n)->new NotificationItem(r.getLong("id"),r.getString("channel"),r.getString("recipient"),r.getString("status"),r.getObject("sent_at",LocalDateTime.class),r.getObject("created_at",LocalDateTime.class))).list();}
    public List<History> history(long id){return jdbc.sql("SELECT h.*,u.full_name FROM invoice_history h LEFT JOIN users u ON u.id=h.performed_by WHERE h.invoice_id=:id ORDER BY h.created_at DESC").param("id",id).query((r,n)->new History(r.getLong("id"),r.getString("action"),r.getString("previous_status"),r.getString("new_status"),r.getString("reason"),r.getString("full_name"),r.getObject("created_at",LocalDateTime.class))).list();}
    public int issue(long id,long actor,long version){return jdbc.sql("UPDATE invoices SET status='ISSUED',issue_date=COALESCE(issue_date,CURRENT_DATE),issued_by=:actor,issued_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=:id AND status IN ('DRAFT','PENDING_REVIEW') AND version=:version").param("actor",actor).param("id",id).param("version",version).update();}
    public long payment(long invoiceId,BigDecimal amount,String method,LocalDateTime paidAt,String reference,String note,long actor){KeyHolder k=new GeneratedKeyHolder();jdbc.sql("INSERT INTO payments(invoice_id,receipt_code,amount,payment_method,reference_code,note,status,received_by,paid_at) VALUES(:invoice,CONCAT('PT-',DATE_FORMAT(NOW(),'%Y%m%d'),'-',LPAD(FLOOR(RAND()*999999),6,'0')),:amount,:method,:reference,:note,'CONFIRMED',:actor,:paidAt)").param("invoice",invoiceId).param("amount",amount).param("method",method).param("reference",blank(reference)).param("note",blank(note)).param("actor",actor).param("paidAt",paidAt).update(k,"id");return k.getKey().longValue();}
    public int applyPayment(long id,BigDecimal amount,long version){return jdbc.sql("UPDATE invoices SET paid_amount=paid_amount+:amount,remaining_amount=GREATEST(total_amount-paid_amount-:amount,0),status=CASE WHEN total_amount-paid_amount-:amount<=0 THEN 'PAID' ELSE 'PARTIALLY_PAID' END,version=version+1 WHERE id=:id AND version=:version AND status NOT IN ('DRAFT','CANCELLED','PAID') AND remaining_amount>=:amount").param("amount",amount).param("id",id).param("version",version).update();}
    public int cancel(long id,String reason,long actor,long version){return jdbc.sql("UPDATE invoices SET status='CANCELLED',cancelled_by=:actor,cancelled_at=CURRENT_TIMESTAMP,cancellation_reason=:reason,version=version+1 WHERE id=:id AND version=:version AND paid_amount=0 AND status NOT IN ('PAID','CANCELLED')").param("actor",actor).param("reason",reason).param("id",id).param("version",version).update();}
    public int adjust(long id,String type,BigDecimal amount,String reason,long actor,long version){BigDecimal signed="INCREASE".equals(type)?amount:amount.negate();int n=jdbc.sql("UPDATE invoices SET total_amount=total_amount+:signed,remaining_amount=remaining_amount+:signed,has_adjustment=TRUE,status=CASE WHEN remaining_amount+:signed=0 THEN 'PAID' WHEN paid_amount>0 THEN 'PARTIALLY_PAID' ELSE status END,version=version+1 WHERE id=:id AND version=:version AND status NOT IN ('DRAFT','CANCELLED') AND total_amount+:signed>=0 AND remaining_amount+:signed>=0").param("signed",signed).param("id",id).param("version",version).update();if(n>0)jdbc.sql("INSERT INTO invoice_adjustments(invoice_id,adjustment_code,adjustment_type,amount,reason,requested_by,approved_by,approved_at) VALUES(:invoice,CONCAT('DC-',DATE_FORMAT(NOW(),'%Y%m%d'),'-',LPAD(FLOOR(RAND()*999999),6,'0')),:type,:amount,:reason,:actor,:actor,CURRENT_TIMESTAMP)").param("invoice",id).param("type",type).param("amount",amount).param("reason",reason).param("actor",actor).update();return n;}
    public void reminder(long id,String channel,String recipient,long actor){jdbc.sql("INSERT INTO invoice_notification_logs(invoice_id,channel,recipient,template_code,status,sent_at,created_by) VALUES(:invoice,:channel,:recipient,'PAYMENT_REMINDER','SENT',CURRENT_TIMESTAMP,:actor)").param("invoice",id).param("channel",channel).param("recipient",recipient).param("actor",actor).update();}
    public void history(long id,String action,String oldStatus,String newStatus,String reason,long actor){jdbc.sql("INSERT INTO invoice_history(invoice_id,action,previous_status,new_status,reason,performed_by) VALUES(:invoice,:action,:old,:new,:reason,:actor)").param("invoice",id).param("action",action).param("old",oldStatus).param("new",newStatus).param("reason",blank(reason)).param("actor",actor).update();}
    public List<Map<String,Object>> roomsForBulk(long propertyId){return jdbc.sql("SELECT r.id,r.code,c.id contract_id,c.tenant_id,r.monthly_rent,u.full_name tenant_name FROM rooms r JOIN contracts c ON c.room_id=r.id AND c.status='ACTIVE' JOIN users u ON u.id=c.tenant_id WHERE r.property_id=:property AND CURRENT_DATE BETWEEN c.start_date AND c.end_date ORDER BY r.code").param("property",propertyId).query(AdminInvoiceRepository::map).list();}
    private InvoiceRow row(ResultSet r)throws SQLException{LocalDate due=r.getObject("due_date",LocalDate.class);long overdue=due!=null&&due.isBefore(LocalDate.now())&&r.getBigDecimal("remaining_amount").signum()>0?java.time.temporal.ChronoUnit.DAYS.between(due,LocalDate.now()):0;return new InvoiceRow(r.getLong("id"),r.getString("code"),r.getString("period"),new Party(r.getLong("property_id"),r.getString("property_name"),null),new Party(r.getLong("room_id"),r.getString("room_code"),r.getString("building_name")+" · "+r.getString("floor_name")),new Party(r.getLong("tenant_id"),r.getString("tenant_name"),r.getString("phone")),new Party(r.getLong("contract_id"),r.getString("contract_code"),null),r.getObject("issue_date",LocalDate.class),due,r.getBigDecimal("total_amount"),r.getBigDecimal("paid_amount"),r.getBigDecimal("remaining_amount"),overdue,r.getString("effective_status"),nullableLong(r,"creator_id")==null?null:new Party(r.getLong("creator_id"),r.getString("creator_name"),null),r.getBoolean("is_automated"),r.getBoolean("has_adjustment"),r.getLong("version"),r.getObject("created_at",LocalDateTime.class));}
    private static Map<String,Object> map(ResultSet r,int n)throws SQLException{Map<String,Object>x=new HashMap<>();var md=r.getMetaData();for(int i=1;i<=md.getColumnCount();i++)x.put(md.getColumnLabel(i),r.getObject(i));return x;}private static Long nullableLong(ResultSet r,String c)throws SQLException{Object x=r.getObject(c);return x==null?null:((Number)x).longValue();}private static Long nullableLong(ResultSet r,int c)throws SQLException{Object x=r.getObject(c);return x==null?null:((Number)x).longValue();}private static String blank(String x){return x==null||x.isBlank()?null:x.trim();}
}
